// Generated by scripts/generate-operations-agent-control-contracts.mjs. Do not edit.

export const OPERATIONS_AGENT_TOOL_CATALOG_VERSION = "operations-agent-tool-catalog/v1" as const;

export const OPERATIONS_AGENT_RUNTIME_READ_TOOLS = [
  "registry.getSite",
  "registry.listSiteAssets",
  "telemetry.getCurrentSnapshot",
  "analytics.getEnergySeries",
  "commands.getCapabilities",
] as const;

export type LogicalTool = typeof OPERATIONS_AGENT_RUNTIME_READ_TOOLS[number];

export const OPERATIONS_AGENT_TOOL_RECEIPT_OWNERS = [
  "registry",
  "telemetry-query-service",
  "command-service",
] as const;

export type ToolOwner = typeof OPERATIONS_AGENT_TOOL_RECEIPT_OWNERS[number];

export const OPERATIONS_AGENT_TOOL_RECEIPT_OWNER_BY_LOGICAL_TOOL = Object.freeze({
  "registry.getSite": "registry",
  "registry.listSiteAssets": "registry",
  "telemetry.getCurrentSnapshot": "telemetry-query-service",
  "analytics.getEnergySeries": "telemetry-query-service",
  "commands.getCapabilities": "command-service",
} as const satisfies Readonly<Record<LogicalTool, ToolOwner>>);
