import type {
  DeviceItem,
  LensNode,
  SystemsDevicesQuery,
} from "./systems-devices-types";

const MOCK_DEVICES: readonly DeviceItem[] = [
  {
    id: "dev-ch-01",
    code: "CH-01",
    name: "1# 高效变频离心式冷水机组",
    category: "chiller",
    categoryLabel: "冷水机组",
    systemId: "sys-chiller-plant",
    systemName: "暖通空调 / 冷热源冷站系统",
    spaceId: "sp-b2-plant",
    spaceName: "地下二层 制冷机房",
    meterId: "M-CH01",
    meterName: "1# 冷机动力配电回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 312.4,
    cop: 5.42,
    loadPercent: 78,
    supplyTemp: 7.0,
    returnTemp: 12.2,
    flowRate: 380,
    activeAlarmsCount: 1,
    activeAlarms: [
      {
        id: "AL-901",
        severity: "warning",
        message: "冷凝器出水温差逼近度稍高 (2.1°C，建议清洗)",
        triggeredAt: "今日 09:15",
      },
    ],
    opportunitiesCount: 1,
    dataHealthPercent: 99.8,
    specs: {
      manufacturer: "特灵 (Trane)",
      model: "CTV-800-HE",
      ratedPowerKw: 420,
      ratedCoolingKw: 2810,
      refrigerant: "R134a",
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "王工 (暖通班长)",
    },
    setpoints: {
      chilledWaterSupplyTemp: 7.0,
      mode: "auto",
      frequencyLimitHz: 50.0,
    },
  },
  {
    id: "dev-ch-02",
    code: "CH-02",
    name: "2# 高效变频离心式冷水机组",
    category: "chiller",
    categoryLabel: "冷水机组",
    systemId: "sys-chiller-plant",
    systemName: "暖通空调 / 冷热源冷站系统",
    spaceId: "sp-b2-plant",
    spaceName: "地下二层 制冷机房",
    meterId: "M-CH02",
    meterName: "2# 冷机动力配电回路",
    status: "standby",
    statusLabel: "备用中",
    powerKw: 0.0,
    cop: undefined,
    loadPercent: 0,
    supplyTemp: 18.5,
    returnTemp: 18.6,
    flowRate: 0,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 100.0,
    specs: {
      manufacturer: "特灵 (Trane)",
      model: "CTV-800-HE",
      ratedPowerKw: 420,
      ratedCoolingKw: 2810,
      refrigerant: "R134a",
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-25",
      responsiblePerson: "王工 (暖通班长)",
    },
    setpoints: {
      chilledWaterSupplyTemp: 7.0,
      mode: "auto",
      frequencyLimitHz: 50.0,
    },
  },
  {
    id: "dev-chwp-01",
    code: "CHP-01",
    name: "1# 一级冷冻水循环水泵",
    category: "pump",
    categoryLabel: "水泵",
    systemId: "sys-hydronic",
    systemName: "空调水输配系统",
    spaceId: "sp-b2-plant",
    spaceName: "地下二层 水泵区",
    meterId: "M-CHP01",
    meterName: "1# 冷冻泵变频动力柜",
    status: "running",
    statusLabel: "运行中",
    powerKw: 38.5,
    cop: undefined,
    loadPercent: 82,
    flowRate: 385,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "格兰富 (Grundfos)",
      model: "NK 150-315",
      ratedPowerKw: 45,
      installDate: "2023-05-20",
      nextMaintenanceDate: "2026-12-10",
      responsiblePerson: "李工 (机电主管)",
    },
    setpoints: {
      mode: "auto",
      frequencyLimitHz: 42.5,
    },
  },
  {
    id: "dev-ct-01",
    code: "CT-01",
    name: "1# 低噪声横流开式冷却塔",
    category: "tower",
    categoryLabel: "冷却塔",
    systemId: "sys-cooling-tower",
    systemName: "冷却水散热系统",
    spaceId: "sp-roof",
    spaceName: "主楼楼顶 设备平台",
    meterId: "M-CT01",
    meterName: "1# 冷却塔风机配电箱",
    status: "running",
    statusLabel: "运行中",
    powerKw: 22.4,
    loadPercent: 75,
    supplyTemp: 32.0,
    returnTemp: 27.5,
    activeAlarmsCount: 0,
    opportunitiesCount: 1,
    dataHealthPercent: 99.2,
    specs: {
      manufacturer: "马利 (Marley)",
      model: "NC-8400",
      ratedPowerKw: 30,
      installDate: "2023-06-10",
      nextMaintenanceDate: "2026-10-15",
      responsiblePerson: "刘工 (运行值班员)",
    },
    setpoints: {
      mode: "auto",
      frequencyLimitHz: 40.0,
    },
  },
  {
    id: "dev-ahu-03",
    code: "AHU-03",
    name: "东塔 8F 变频空调箱 (AHU)",
    category: "ahu",
    categoryLabel: "空气处理机",
    systemId: "sys-terminal-ahu",
    systemName: "末端空气处理系统",
    spaceId: "sp-east-8f",
    spaceName: "东塔 8F 空调机房",
    meterId: "M-AHU-E8",
    meterName: "东塔 8F 空调配电箱",
    status: "running",
    statusLabel: "运行中",
    powerKw: 18.2,
    loadPercent: 65,
    supplyTemp: 14.2,
    returnTemp: 24.5,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.9,
    specs: {
      manufacturer: "开利 (Carrier)",
      model: "39G-120",
      ratedPowerKw: 22,
      installDate: "2023-07-01",
      nextMaintenanceDate: "2026-10-30",
      responsiblePerson: "陈工 (楼宇自控)",
    },
    setpoints: {
      chilledWaterSupplyTemp: 14.0,
      mode: "auto",
      frequencyLimitHz: 38.0,
    },
  },
  {
    id: "dev-ahu-04",
    code: "AHU-04",
    name: "西塔 12F 变频空调箱 (AHU)",
    category: "ahu",
    categoryLabel: "空气处理机",
    systemId: "sys-terminal-ahu",
    systemName: "末端空气处理系统",
    spaceId: "sp-west-12f",
    spaceName: "西塔 12F 空调机房",
    meterId: "M-AHU-W12",
    meterName: "西塔 12F 空调配电箱",
    status: "alarm",
    statusLabel: "诊断异常",
    powerKw: 19.8,
    loadPercent: 72,
    supplyTemp: 13.8,
    returnTemp: 25.1,
    activeAlarmsCount: 1,
    activeAlarms: [
      {
        id: "AL-AHU04",
        severity: "warning",
        message: "风机非排程时段持续全风量运行，存在冷量过度供应",
        triggeredAt: "今日 06:15",
      },
    ],
    opportunitiesCount: 1,
    dataHealthPercent: 98.4,
    specs: {
      manufacturer: "开利 (Carrier)",
      model: "39G-120",
      ratedPowerKw: 22,
      installDate: "2023-07-01",
      nextMaintenanceDate: "2026-10-25",
      responsiblePerson: "陈工 (楼宇自控)",
    },
    setpoints: {
      chilledWaterSupplyTemp: 14.0,
      mode: "manual",
      frequencyLimitHz: 45.0,
    },
  },
  {
    id: "TX-01",
    code: "TX-01",
    name: "1# 环氧树脂干式变压器 (2000kVA)",
    category: "transformer",
    categoryLabel: "变配电",
    systemId: "sys-power-dist",
    systemName: "变配电系统",
    spaceId: "sp-b1-power",
    spaceName: "地下一层 变配电总室",
    meterId: "M-MAIN-01",
    meterName: "1# 10kV 进线高压计量总柜",
    status: "running",
    statusLabel: "运行中",
    powerKw: 1240.0,
    loadPercent: 62,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 100.0,
    specs: {
      manufacturer: "施耐德 (Schneider)",
      model: "SCB11-2000/10",
      ratedPowerKw: 1600,
      installDate: "2023-04-10",
      nextMaintenanceDate: "2027-04-10",
      responsiblePerson: "赵工 (值班电工)",
    },
    setpoints: {
      mode: "auto",
    },
  },
  {
    id: "dev-ct-03",
    code: "CT-03",
    name: "3# 闭式冷却塔",
    category: "tower",
    categoryLabel: "冷却塔",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-CT-03",
    meterName: "3# 闭式冷却塔计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 15.2,
    loadPercent: 80,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 15.2,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
  {
    id: "dev-chwp-02",
    code: "CHWP-02",
    name: "2# 定速冷冻水泵",
    category: "pump",
    categoryLabel: "水泵",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-CHWP-02",
    meterName: "2# 定速冷冻水泵计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 35.8,
    loadPercent: 70,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 35.8,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
  {
    id: "dev-cwp-01",
    code: "CWP-01",
    name: "1# 变频冷却水泵",
    category: "pump",
    categoryLabel: "水泵",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-CWP-01",
    meterName: "1# 变频冷却水泵计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 44.5,
    loadPercent: 65,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 44.5,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
  {
    id: "dev-pau-02",
    code: "PAU-02",
    name: "PAU-02 新风处理机组",
    category: "ahu",
    categoryLabel: "空气处理机组",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-PAU-02",
    meterName: "PAU-02 新风处理机组计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 12.5,
    loadPercent: 75,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 12.5,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
  {
    id: "dev-hex-01",
    code: "HEX-01",
    name: "HEX-01 板式换热器",
    category: "heat-exchanger",
    categoryLabel: "板式换热器",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-HEX-01",
    meterName: "HEX-01 板式换热器计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 0,
    loadPercent: 60,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 0,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
  {
    id: "dev-chem-01",
    code: "CHEM-01",
    name: "冷水与冷却水加药装置",
    category: "dosing",
    categoryLabel: "水处理装置",
    systemId: "sys-hvac",
    systemName: "暖通空调",
    spaceId: "sp-plant",
    spaceName: "上海恒隆广场机房",
    meterId: "meter-CHEM-01",
    meterName: "冷水与冷却水加药装置计量回路",
    status: "running",
    statusLabel: "运行中",
    powerKw: 1.2,
    loadPercent: 40,
    activeAlarmsCount: 0,
    opportunitiesCount: 0,
    dataHealthPercent: 99.5,
    specs: {
      manufacturer: "未登记",
      model: "未登记",
      ratedPowerKw: 1.2,
      installDate: "2023-05-18",
      nextMaintenanceDate: "2026-11-20",
      responsiblePerson: "暖通维保班",
    },
    setpoints: { mode: "auto" },
  },
];

const MOCK_LENS_TREE: Record<
  "space" | "system" | "equipment" | "meter",
  readonly LensNode[]
> = {
  space: [
    {
      id: "sp-all",
      name: "全部建筑空间",
      type: "space",
      count: 7,
      children: [
        {
          id: "sp-b2",
          name: "地下二层 (B2 冷热源区)",
          type: "space",
          count: 3,
        },
        {
          id: "sp-b1",
          name: "地下一层 (B1 配电区)",
          type: "space",
          count: 1,
        },
        {
          id: "sp-tower-east",
          name: "主楼东塔办公区",
          type: "space",
          count: 1,
        },
        {
          id: "sp-tower-west",
          name: "主楼西塔办公区",
          type: "space",
          count: 1,
        },
        {
          id: "sp-roof",
          name: "楼顶设备平台",
          type: "space",
          count: 1,
        },
      ],
    },
  ],
  system: [
    {
      id: "sys-all",
      name: "全站用能系统",
      type: "system",
      count: 7,
      children: [
        {
          id: "sys-chiller-plant",
          name: "暖通空调 / 冷热源冷站系统",
          type: "system",
          count: 2,
        },
        {
          id: "sys-hydronic",
          name: "空调水输配循环系统",
          type: "system",
          count: 1,
        },
        {
          id: "sys-cooling-tower",
          name: "冷却水散热系统",
          type: "system",
          count: 1,
        },
        {
          id: "sys-terminal-ahu",
          name: "末端空气处理系统 (AHU)",
          type: "system",
          count: 2,
        },
        {
          id: "sys-power-dist",
          name: "高低压变配电系统",
          type: "system",
          count: 1,
        },
      ],
    },
  ],
  equipment: [
    {
      id: "eq-all",
      name: "全部物理机电设备",
      type: "equipment",
      count: 7,
      children: [
        {
          id: "cat-chiller",
          name: "离心冷水机组",
          type: "equipment",
          count: 2,
        },
        { id: "cat-pump", name: "水泵泵组", type: "equipment", count: 1 },
        { id: "cat-tower", name: "冷却塔", type: "equipment", count: 1 },
        { id: "cat-ahu", name: "空气处理机箱", type: "equipment", count: 2 },
        { id: "cat-transformer", name: "变压器", type: "equipment", count: 1 },
      ],
    },
  ],
  meter: [
    {
      id: "m-all",
      name: "计量回路拓扑网络",
      type: "meter",
      count: 7,
      children: [
        {
          id: "m-level1",
          name: "一级进线总表 (10kV)",
          type: "meter",
          count: 1,
        },
        {
          id: "m-level2-hvac",
          name: "二级暖通动力分项表",
          type: "meter",
          count: 4,
        },
        {
          id: "m-level3-terminal",
          name: "三级末端分配电箱",
          type: "meter",
          count: 2,
        },
      ],
    },
  ],
};

export const systemsDevicesService = {
  async getDevices(
    query: SystemsDevicesQuery = {},
  ): Promise<readonly DeviceItem[]> {
    await new Promise((resolve) => setTimeout(resolve, 60));

    let results = [...MOCK_DEVICES];

    if (query.search) {
      const s = query.search.toLowerCase();
      results = results.filter(
        (d) =>
          d.name.toLowerCase().includes(s) ||
          d.code.toLowerCase().includes(s) ||
          d.spaceName.toLowerCase().includes(s) ||
          d.systemName.toLowerCase().includes(s) ||
          d.specs.manufacturer.toLowerCase().includes(s),
      );
    }

    if (query.category && query.category !== "all") {
      results = results.filter((d) => d.category === query.category);
    }

    if (query.status && query.status !== "all") {
      results = results.filter((d) => d.status === query.status);
    }

    return results;
  },

  async getDeviceById(id: string): Promise<DeviceItem | undefined> {
    await new Promise((resolve) => setTimeout(resolve, 40));
    return MOCK_DEVICES.find((d) => d.id === id);
  },

  async getLensTree(
    lens: "space" | "system" | "equipment" | "meter",
  ): Promise<readonly LensNode[]> {
    await new Promise((resolve) => setTimeout(resolve, 30));
    return MOCK_LENS_TREE[lens];
  },
};
