/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSiteRouteImport } from './routes/_app._site'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppSystemRouteImport } from './routes/_app.system'
import { Route as AppSiteOverviewRouteImport } from './routes/_app._site.overview'
import { Route as AppSiteReportsRouteImport } from './routes/_app._site.reports'
import { Route as AppSettingsAccessRouteImport } from './routes/_app.settings.access'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsSitesRouteImport } from './routes/_app.settings.sites'
import { Route as AppSiteEnergyAnalysisBenchmarkingRouteImport } from './routes/_app._site.energy-analysis.benchmarking'
import { Route as AppSiteEnergyAnalysisBreakdownRouteImport } from './routes/_app._site.energy-analysis.breakdown'
import { Route as AppSiteEnergyAnalysisConsumptionRouteImport } from './routes/_app._site.energy-analysis.consumption'
import { Route as AppSiteEnergyAnalysisLoadDemandRouteImport } from './routes/_app._site.energy-analysis.load-demand'
import { Route as AppSiteOperationsAlarmsRouteImport } from './routes/_app._site.operations.alarms'
import { Route as AppSiteOperationsControlRouteImport } from './routes/_app._site.operations.control'
import { Route as AppSiteOperationsRealtimeRouteImport } from './routes/_app._site.operations.realtime'
import { Route as AppSiteOperationsSystemsDevicesRouteImport } from './routes/_app._site.operations.systems-devices'
import { Route as AppSiteOperationsWorkCenterRouteImport } from './routes/_app._site.operations.work-center'
import { Route as AppSiteOptimizationOpportunitiesRouteImport } from './routes/_app._site.optimization.opportunities'
import { Route as AppSiteOptimizationProjectsRouteImport } from './routes/_app._site.optimization.projects'
import { Route as AppSiteOptimizationVerificationRouteImport } from './routes/_app._site.optimization.verification'
import { Route as AppSiteSettingsIndexRouteImport } from './routes/_app._site.settings.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteOverviewRoute = AppSiteOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteReportsRoute = AppSiteReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSettingsAccessRoute = AppSettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSitesRoute = AppSettingsSitesRouteImport.update({
  id: '/settings/sites',
  path: '/settings/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteEnergyAnalysisBenchmarkingRoute =
  AppSiteEnergyAnalysisBenchmarkingRouteImport.update({
    id: '/energy-analysis/benchmarking',
    path: '/energy-analysis/benchmarking',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteEnergyAnalysisBreakdownRoute =
  AppSiteEnergyAnalysisBreakdownRouteImport.update({
    id: '/energy-analysis/breakdown',
    path: '/energy-analysis/breakdown',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteEnergyAnalysisConsumptionRoute =
  AppSiteEnergyAnalysisConsumptionRouteImport.update({
    id: '/energy-analysis/consumption',
    path: '/energy-analysis/consumption',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteEnergyAnalysisLoadDemandRoute =
  AppSiteEnergyAnalysisLoadDemandRouteImport.update({
    id: '/energy-analysis/load-demand',
    path: '/energy-analysis/load-demand',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOperationsAlarmsRoute = AppSiteOperationsAlarmsRouteImport.update({
  id: '/operations/alarms',
  path: '/operations/alarms',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteOperationsControlRoute =
  AppSiteOperationsControlRouteImport.update({
    id: '/operations/control',
    path: '/operations/control',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOperationsRealtimeRoute =
  AppSiteOperationsRealtimeRouteImport.update({
    id: '/operations/realtime',
    path: '/operations/realtime',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOperationsSystemsDevicesRoute =
  AppSiteOperationsSystemsDevicesRouteImport.update({
    id: '/operations/systems-devices',
    path: '/operations/systems-devices',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOperationsWorkCenterRoute =
  AppSiteOperationsWorkCenterRouteImport.update({
    id: '/operations/work-center',
    path: '/operations/work-center',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOptimizationOpportunitiesRoute =
  AppSiteOptimizationOpportunitiesRouteImport.update({
    id: '/optimization/opportunities',
    path: '/optimization/opportunities',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOptimizationProjectsRoute =
  AppSiteOptimizationProjectsRouteImport.update({
    id: '/optimization/projects',
    path: '/optimization/projects',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteOptimizationVerificationRoute =
  AppSiteOptimizationVerificationRouteImport.update({
    id: '/optimization/verification',
    path: '/optimization/verification',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteSettingsIndexRoute = AppSiteSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppSiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/notifications': typeof AppNotificationsRoute
  '/system': typeof AppSystemRoute
  '/overview': typeof AppSiteOverviewRoute
  '/reports': typeof AppSiteReportsRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/sites': typeof AppSettingsSitesRoute
  '/energy-analysis/benchmarking': typeof AppSiteEnergyAnalysisBenchmarkingRoute
  '/energy-analysis/breakdown': typeof AppSiteEnergyAnalysisBreakdownRoute
  '/energy-analysis/consumption': typeof AppSiteEnergyAnalysisConsumptionRoute
  '/energy-analysis/load-demand': typeof AppSiteEnergyAnalysisLoadDemandRoute
  '/operations/alarms': typeof AppSiteOperationsAlarmsRoute
  '/operations/control': typeof AppSiteOperationsControlRoute
  '/operations/realtime': typeof AppSiteOperationsRealtimeRoute
  '/operations/systems-devices': typeof AppSiteOperationsSystemsDevicesRoute
  '/operations/work-center': typeof AppSiteOperationsWorkCenterRoute
  '/optimization/opportunities': typeof AppSiteOptimizationOpportunitiesRoute
  '/optimization/projects': typeof AppSiteOptimizationProjectsRoute
  '/optimization/verification': typeof AppSiteOptimizationVerificationRoute
  '/settings/': typeof AppSiteSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/notifications': typeof AppNotificationsRoute
  '/system': typeof AppSystemRoute
  '/overview': typeof AppSiteOverviewRoute
  '/reports': typeof AppSiteReportsRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/sites': typeof AppSettingsSitesRoute
  '/energy-analysis/benchmarking': typeof AppSiteEnergyAnalysisBenchmarkingRoute
  '/energy-analysis/breakdown': typeof AppSiteEnergyAnalysisBreakdownRoute
  '/energy-analysis/consumption': typeof AppSiteEnergyAnalysisConsumptionRoute
  '/energy-analysis/load-demand': typeof AppSiteEnergyAnalysisLoadDemandRoute
  '/operations/alarms': typeof AppSiteOperationsAlarmsRoute
  '/operations/control': typeof AppSiteOperationsControlRoute
  '/operations/realtime': typeof AppSiteOperationsRealtimeRoute
  '/operations/systems-devices': typeof AppSiteOperationsSystemsDevicesRoute
  '/operations/work-center': typeof AppSiteOperationsWorkCenterRoute
  '/optimization/opportunities': typeof AppSiteOptimizationOpportunitiesRoute
  '/optimization/projects': typeof AppSiteOptimizationProjectsRoute
  '/optimization/verification': typeof AppSiteOptimizationVerificationRoute
  '/settings': typeof AppSiteSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_site': typeof AppSiteRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_site/overview': typeof AppSiteOverviewRoute
  '/_app/_site/reports': typeof AppSiteReportsRoute
  '/_app/settings/access': typeof AppSettingsAccessRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/sites': typeof AppSettingsSitesRoute
  '/_app/_site/energy-analysis/benchmarking': typeof AppSiteEnergyAnalysisBenchmarkingRoute
  '/_app/_site/energy-analysis/breakdown': typeof AppSiteEnergyAnalysisBreakdownRoute
  '/_app/_site/energy-analysis/consumption': typeof AppSiteEnergyAnalysisConsumptionRoute
  '/_app/_site/energy-analysis/load-demand': typeof AppSiteEnergyAnalysisLoadDemandRoute
  '/_app/_site/operations/alarms': typeof AppSiteOperationsAlarmsRoute
  '/_app/_site/operations/control': typeof AppSiteOperationsControlRoute
  '/_app/_site/operations/realtime': typeof AppSiteOperationsRealtimeRoute
  '/_app/_site/operations/systems-devices': typeof AppSiteOperationsSystemsDevicesRoute
  '/_app/_site/operations/work-center': typeof AppSiteOperationsWorkCenterRoute
  '/_app/_site/optimization/opportunities': typeof AppSiteOptimizationOpportunitiesRoute
  '/_app/_site/optimization/projects': typeof AppSiteOptimizationProjectsRoute
  '/_app/_site/optimization/verification': typeof AppSiteOptimizationVerificationRoute
  '/_app/_site/settings/': typeof AppSiteSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/system'
    | '/overview'
    | '/reports'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/sites'
    | '/energy-analysis/benchmarking'
    | '/energy-analysis/breakdown'
    | '/energy-analysis/consumption'
    | '/energy-analysis/load-demand'
    | '/operations/alarms'
    | '/operations/control'
    | '/operations/realtime'
    | '/operations/systems-devices'
    | '/operations/work-center'
    | '/optimization/opportunities'
    | '/optimization/projects'
    | '/optimization/verification'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/system'
    | '/overview'
    | '/reports'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/sites'
    | '/energy-analysis/benchmarking'
    | '/energy-analysis/breakdown'
    | '/energy-analysis/consumption'
    | '/energy-analysis/load-demand'
    | '/operations/alarms'
    | '/operations/control'
    | '/operations/realtime'
    | '/operations/systems-devices'
    | '/operations/work-center'
    | '/optimization/opportunities'
    | '/optimization/projects'
    | '/optimization/verification'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_site'
    | '/_app/notifications'
    | '/_app/system'
    | '/_app/'
    | '/_app/_site/overview'
    | '/_app/_site/reports'
    | '/_app/settings/access'
    | '/_app/settings/integrations'
    | '/_app/settings/sites'
    | '/_app/_site/energy-analysis/benchmarking'
    | '/_app/_site/energy-analysis/breakdown'
    | '/_app/_site/energy-analysis/consumption'
    | '/_app/_site/energy-analysis/load-demand'
    | '/_app/_site/operations/alarms'
    | '/_app/_site/operations/control'
    | '/_app/_site/operations/realtime'
    | '/_app/_site/operations/systems-devices'
    | '/_app/_site/operations/work-center'
    | '/_app/_site/optimization/opportunities'
    | '/_app/_site/optimization/projects'
    | '/_app/_site/optimization/verification'
    | '/_app/_site/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_site': {
      id: '/_app/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_site/overview': {
      id: '/_app/_site/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppSiteOverviewRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/reports': {
      id: '/_app/_site/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppSiteReportsRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/settings/access': {
      id: '/_app/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AppSettingsAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/sites': {
      id: '/_app/settings/sites'
      path: '/settings/sites'
      fullPath: '/settings/sites'
      preLoaderRoute: typeof AppSettingsSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_site/energy-analysis/benchmarking': {
      id: '/_app/_site/energy-analysis/benchmarking'
      path: '/energy-analysis/benchmarking'
      fullPath: '/energy-analysis/benchmarking'
      preLoaderRoute: typeof AppSiteEnergyAnalysisBenchmarkingRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/energy-analysis/breakdown': {
      id: '/_app/_site/energy-analysis/breakdown'
      path: '/energy-analysis/breakdown'
      fullPath: '/energy-analysis/breakdown'
      preLoaderRoute: typeof AppSiteEnergyAnalysisBreakdownRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/energy-analysis/consumption': {
      id: '/_app/_site/energy-analysis/consumption'
      path: '/energy-analysis/consumption'
      fullPath: '/energy-analysis/consumption'
      preLoaderRoute: typeof AppSiteEnergyAnalysisConsumptionRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/energy-analysis/load-demand': {
      id: '/_app/_site/energy-analysis/load-demand'
      path: '/energy-analysis/load-demand'
      fullPath: '/energy-analysis/load-demand'
      preLoaderRoute: typeof AppSiteEnergyAnalysisLoadDemandRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/operations/alarms': {
      id: '/_app/_site/operations/alarms'
      path: '/operations/alarms'
      fullPath: '/operations/alarms'
      preLoaderRoute: typeof AppSiteOperationsAlarmsRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/operations/control': {
      id: '/_app/_site/operations/control'
      path: '/operations/control'
      fullPath: '/operations/control'
      preLoaderRoute: typeof AppSiteOperationsControlRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/operations/realtime': {
      id: '/_app/_site/operations/realtime'
      path: '/operations/realtime'
      fullPath: '/operations/realtime'
      preLoaderRoute: typeof AppSiteOperationsRealtimeRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/operations/systems-devices': {
      id: '/_app/_site/operations/systems-devices'
      path: '/operations/systems-devices'
      fullPath: '/operations/systems-devices'
      preLoaderRoute: typeof AppSiteOperationsSystemsDevicesRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/operations/work-center': {
      id: '/_app/_site/operations/work-center'
      path: '/operations/work-center'
      fullPath: '/operations/work-center'
      preLoaderRoute: typeof AppSiteOperationsWorkCenterRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/optimization/opportunities': {
      id: '/_app/_site/optimization/opportunities'
      path: '/optimization/opportunities'
      fullPath: '/optimization/opportunities'
      preLoaderRoute: typeof AppSiteOptimizationOpportunitiesRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/optimization/projects': {
      id: '/_app/_site/optimization/projects'
      path: '/optimization/projects'
      fullPath: '/optimization/projects'
      preLoaderRoute: typeof AppSiteOptimizationProjectsRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/optimization/verification': {
      id: '/_app/_site/optimization/verification'
      path: '/optimization/verification'
      fullPath: '/optimization/verification'
      preLoaderRoute: typeof AppSiteOptimizationVerificationRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/settings/': {
      id: '/_app/_site/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSiteSettingsIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
  }
}

interface AppSiteRouteChildren {
  AppSiteOverviewRoute: typeof AppSiteOverviewRoute
  AppSiteReportsRoute: typeof AppSiteReportsRoute
  AppSiteEnergyAnalysisBenchmarkingRoute: typeof AppSiteEnergyAnalysisBenchmarkingRoute
  AppSiteEnergyAnalysisBreakdownRoute: typeof AppSiteEnergyAnalysisBreakdownRoute
  AppSiteEnergyAnalysisConsumptionRoute: typeof AppSiteEnergyAnalysisConsumptionRoute
  AppSiteEnergyAnalysisLoadDemandRoute: typeof AppSiteEnergyAnalysisLoadDemandRoute
  AppSiteOperationsAlarmsRoute: typeof AppSiteOperationsAlarmsRoute
  AppSiteOperationsControlRoute: typeof AppSiteOperationsControlRoute
  AppSiteOperationsRealtimeRoute: typeof AppSiteOperationsRealtimeRoute
  AppSiteOperationsSystemsDevicesRoute: typeof AppSiteOperationsSystemsDevicesRoute
  AppSiteOperationsWorkCenterRoute: typeof AppSiteOperationsWorkCenterRoute
  AppSiteOptimizationOpportunitiesRoute: typeof AppSiteOptimizationOpportunitiesRoute
  AppSiteOptimizationProjectsRoute: typeof AppSiteOptimizationProjectsRoute
  AppSiteOptimizationVerificationRoute: typeof AppSiteOptimizationVerificationRoute
  AppSiteSettingsIndexRoute: typeof AppSiteSettingsIndexRoute
}

const AppSiteRouteChildren: AppSiteRouteChildren = {
  AppSiteOverviewRoute: AppSiteOverviewRoute,
  AppSiteReportsRoute: AppSiteReportsRoute,
  AppSiteEnergyAnalysisBenchmarkingRoute:
    AppSiteEnergyAnalysisBenchmarkingRoute,
  AppSiteEnergyAnalysisBreakdownRoute: AppSiteEnergyAnalysisBreakdownRoute,
  AppSiteEnergyAnalysisConsumptionRoute: AppSiteEnergyAnalysisConsumptionRoute,
  AppSiteEnergyAnalysisLoadDemandRoute: AppSiteEnergyAnalysisLoadDemandRoute,
  AppSiteOperationsAlarmsRoute: AppSiteOperationsAlarmsRoute,
  AppSiteOperationsControlRoute: AppSiteOperationsControlRoute,
  AppSiteOperationsRealtimeRoute: AppSiteOperationsRealtimeRoute,
  AppSiteOperationsSystemsDevicesRoute: AppSiteOperationsSystemsDevicesRoute,
  AppSiteOperationsWorkCenterRoute: AppSiteOperationsWorkCenterRoute,
  AppSiteOptimizationOpportunitiesRoute: AppSiteOptimizationOpportunitiesRoute,
  AppSiteOptimizationProjectsRoute: AppSiteOptimizationProjectsRoute,
  AppSiteOptimizationVerificationRoute: AppSiteOptimizationVerificationRoute,
  AppSiteSettingsIndexRoute: AppSiteSettingsIndexRoute,
}

const AppSiteRouteWithChildren =
  AppSiteRoute._addFileChildren(AppSiteRouteChildren)

interface AppRouteChildren {
  AppSiteRoute: typeof AppSiteRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsAccessRoute: typeof AppSettingsAccessRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsSitesRoute: typeof AppSettingsSitesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSiteRoute: AppSiteRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSystemRoute: AppSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsAccessRoute: AppSettingsAccessRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsSitesRoute: AppSettingsSitesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
