import { domainModule } from '../domain/index.js';

export {
  InvestigationBusinessRecordError,
  createInvestigationBusinessRecord,
  type AnalysisReferenceRecord,
  type EvidenceRecord,
  type EvidenceSourceReference,
  type FindingRecord,
  type FindingRequiredNext,
  type FindingRequiredNextPeriod,
  type InvestigationBusinessRecord,
  type InvestigationBusinessRecordErrorCode,
  type InvestigationBusinessRecordType,
  type ToolExecutionReceiptRecord,
} from '../domain/index.js';

export {
  InvestigationCoordinatorError,
  createInvestigationCoordinator,
  type AdvanceInvestigationCommand,
  type AdvanceInvestigationResult,
  type CancelInvestigationCommand,
  type CommitInvestigationEffectCommand,
  type CommitInvestigationEffectResult,
  type CreateInvestigationCommand,
  type GetInvestigationQuery,
  type InvestigationCoordinator,
  type InvestigationCoordinatorErrorCode,
  type ReopenInvestigationCommand,
  type ResumeInvestigationCommand,
  type RunLeaseMutationCommand,
  type StartInvestigationCommand,
} from './internal/investigation-coordinator.js';

export {
  NightEnergyAnalysisError,
  analyzeSiteNightEnergy,
  planSiteNightEnergyPeriods,
  type EquipmentAttributionRequiredNext,
  type NightEnergyAnalysisErrorCode,
  type NightEnergyEvidenceDraft,
  type NightEnergyGranularity,
  type NightEnergyQualityPolicy,
  type NightEnergyQualitySummary,
  type NightEnergyReadinessBlocker,
  type NightEnergyReadinessBlockerCode,
  type NightEnergySeries,
  type NightEnergySeriesMetadata,
  type NightEnergySeriesPoint,
  type SiteNightEnergyAnalysisInput,
  type SiteNightEnergyAnalysisReference,
  type SiteNightEnergyAnalysisResult,
  type SiteNightEnergyComparison,
  type SiteNightEnergyFindingDraft,
  type SiteNightEnergyPeriodPlan,
  type SiteNightEnergyPeriodReference,
  type SiteNightEnergyScope,
  type SiteNightEnergyWindow,
  type SupportedSiteNightEnergyAnalysis,
  type UnableSiteNightEnergyAnalysis,
  type UnsupportedEquipmentAttribution,
} from './internal/night-energy-analysis.js';

export {
  createSiteNightEnergyInvestigationCoordinator,
  type ListSiteNightEnergyInvestigationsQuery,
  type SiteNightEnergyActiveRunView,
  type SiteNightEnergyInvestigationCoordinator,
  type SiteNightEnergyInvestigationCoordinatorPorts,
  type SiteNightEnergyInvestigationList,
  type SiteNightEnergyInvestigationPolicy,
  type SiteNightEnergyInvestigationQuery,
  type SiteNightEnergyInvestigationSummary,
  type SiteNightEnergyInvestigationView,
  type StartSiteNightEnergyInvestigationCommand,
} from './internal/site-night-energy-investigation.js';

export {
  InvestigationRepositoryConflictError,
  OwnerReadError,
  type AgentExecutionRuntime,
  type ApplicationEvent,
  type ApplicationOutbox,
  type AuditRecord,
  type AuditRecorder,
  type AuthorizationDecision,
  type AuthorizationDecisionReader,
  type BudgetDecision,
  type BudgetGuard,
  type CheckpointRepository,
  type Clock,
  type CommandCapabilityReadRequest,
  type CommandCapabilityReader,
  type CurrentTelemetryReadRequest,
  type CurrentTelemetryReader,
  type EnergyAnalyticsReadRequest,
  type EnergyAnalyticsReader,
  type GeneratedIdentityKind,
  type IdGenerator,
  type InvestigationAuthorizationAction,
  type InvestigationBusinessRecordRepository,
  type InvestigationCoordinatorPorts,
  type InvestigationRepository,
  type InvestigationRepositoryConflictCode,
  type InvestigationTransaction,
  type InvestigationWriteAuthority,
  type OwnerReadContext,
  type OwnerReadErrorCode,
  type OwnerReadInput,
  type OwnerReadResult,
  type OwnerReaders,
  type ParallelReadBatch,
  type ParallelReadRequest,
  type RegistryReadRequest,
  type RegistryReader,
  type RuntimeCheckpoint,
  type RuntimeCheckpointDraft,
  type RuntimePlanningResult,
  type RuntimeReadPlan,
  type ToolAuthorizationGrant,
  type ToolAuthorizationReader,
} from './internal/ports.js';

export const applicationModule = Object.freeze({
  name: 'application',
  layer: 'application',
  dependencies: [domainModule.name],
} as const);

export type ApplicationModule = typeof applicationModule;
