import { domainModule } from '../domain/index.js';

export {
  OPERATIONS_AGENT_RUNTIME_READ_TOOLS,
  OPERATIONS_AGENT_TOOL_CATALOG_VERSION,
  OPERATIONS_AGENT_TOOL_RECEIPT_OWNER_BY_LOGICAL_TOOL,
  OPERATIONS_AGENT_TOOL_RECEIPT_OWNERS,
  InvestigationBusinessRecordError,
  createInvestigationBusinessRecord,
  type AnalysisReferenceRecord,
  type EvidenceRecord,
  type EvidenceSourceReference,
  type FindingRecord,
  type FindingRequiredNext,
  type FindingRequiredNextPeriod,
  type FindingSynthesisMetering,
  type FindingSynthesisProvenance,
  type InvestigationBusinessRecord,
  type InvestigationBusinessRecordErrorCode,
  type InvestigationBusinessRecordType,
  type OperatorInputAcceptedProvenance,
  type OperatorInputAcceptedRecord,
  type OperatorInputAcceptedValues,
  type OperatorInputRequestView,
  type ToolExecutionReceiptRecord,
} from '../domain/index.js';

export {
  OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTEXT_ID,
  OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTEXT_KEYS,
  OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTROL_POLICY,
  OPERATIONS_AGENT_TRUSTED_RUNTIME_MAXIMUM_IDENTITY_CHARACTERS,
  OPERATIONS_AGENT_TRUSTED_RUNTIME_SCOPE_KEYS,
} from './internal/generated-runtime-control-contract.js';

export {
  FINDING_SYNTHESIS_DEFAULT_TIMEOUT_MS,
  FINDING_SYNTHESIS_OUTPUT_SCHEMA_VERSION,
  FINDING_SYNTHESIS_PROMPT_POLICY_VERSION,
  synthesizeFinding,
  type FindingSynthesisClassification,
  type FindingSynthesisDecision,
  type FindingSynthesisFallbackReason,
  type FindingSynthesisInput,
  type FindingSynthesisProviderMetadata,
  type FindingSynthesisProviderResponse,
  type FindingSynthesizer,
  type FindingSynthesizerDescriptor,
  type SynthesizeFindingInput,
} from './internal/finding-synthesis.js';

export {
  InvestigationCoordinatorError,
  createInvestigationCoordinator,
  type AcceptOperatorInputCommand,
  type AcceptOperatorInputResult,
  type AdvanceInvestigationCommand,
  type AdvanceInvestigationResult,
  type CancelInvestigationCommand,
  type CommitInvestigationEffectCommand,
  type CommitInvestigationEffectResult,
  type CreateInvestigationCommand,
  type GetInvestigationQuery,
  type InvestigationCoordinator,
  type InvestigationCoordinatorErrorCode,
  type ReopenInvestigationCommand,
  type RequestOperatorInputCommand,
  type ResumeInvestigationCommand,
  type RunLeaseMutationCommand,
  type StartInvestigationCommand,
} from './internal/investigation-coordinator.js';

export {
  NightEnergyAnalysisError,
  analyzeSiteNightEnergy,
  planSiteNightEnergyPeriods,
  type AssetAttributionRequiredNext,
  type NightEnergyAnalysisErrorCode,
  type NightEnergyEvidenceDraft,
  type NightEnergyGranularity,
  type NightEnergyQualityPolicy,
  type NightEnergyQualitySummary,
  type NightEnergyReadinessBlocker,
  type NightEnergyReadinessBlockerCode,
  type NightEnergySeries,
  type NightEnergySeriesMetadata,
  type NightEnergySeriesPoint,
  type SiteNightEnergyAnalysisInput,
  type SiteNightEnergyAnalysisReference,
  type SiteNightEnergyAnalysisResult,
  type SiteNightEnergyComparison,
  type SiteNightEnergyFindingDraft,
  type SiteNightEnergyPeriodPlan,
  type SiteNightEnergyPeriodReference,
  type SiteNightEnergyScope,
  type SiteNightEnergyWindow,
  type SupportedSiteNightEnergyAnalysis,
  type UnableSiteNightEnergyAnalysis,
  type UnsupportedAssetAttribution,
} from './internal/night-energy-analysis.js';

export {
  createSiteNightEnergyInvestigationCoordinator,
  type AcceptSiteNightEnergyOperatorInputCommand,
  type AcceptSiteNightEnergyOperatorInputResult,
  type ListSiteNightEnergyInvestigationsQuery,
  type SiteNightEnergyActiveRunView,
  type SiteNightEnergyFindingView,
  type SiteNightEnergyInvestigationCoordinator,
  type SiteNightEnergyInvestigationCoordinatorPorts,
  type SiteNightEnergyInvestigationList,
  type SiteNightEnergyInvestigationPolicy,
  type SiteNightEnergyInvestigationQuery,
  type SiteNightEnergyInvestigationSummary,
  type SiteNightEnergyInvestigationView,
  type StartSiteNightEnergyInvestigationCommand,
} from './internal/site-night-energy-investigation.js';

export {
  DEFAULT_RUN_RESOURCE_BUDGET_POLICY,
  ZERO_RUN_RESOURCE_BUDGET_COST,
  createInMemoryRunResourceBudgetGuard,
  createRunResourceBudgetSnapshot,
  evaluateRunResourceBudgetCheck,
  normalizeRunResourceBudgetCost,
  normalizeRunResourceBudgetPolicy,
  runResourceEffectOperationId,
  runResourceOwnerResultBatchCost,
  runResourceOwnerResultBatchOperationId,
  runResourceOwnerResultCost,
  runResourceOwnerResultOperationId,
  runResourceReadBatchCost,
  runResourceReadBatchOperationId,
  toRunResourceBudgetOutcome,
} from './internal/run-resource-budget.js';

export {
  OPERATIONS_AUDIT_MESSAGE_TYPE,
  OPERATIONS_AUDIT_PRODUCER,
  OPERATIONS_AUDIT_SCHEMA_VERSION,
  createOperationsAuditEvent,
  operationsAuditEventId,
  parseOperationsAuditEvent,
  type CreateOperationsAuditEventInput,
  type OperationsAuditActor,
  type OperationsAuditActorType,
  type OperationsAuditEventV1,
  type OperationsAuditOperation,
  type OperationsAuditOutcome,
  type OperationsAuditRecordReference,
  type OperationsAuditRecordType,
} from './internal/operations-audit.js';

export {
  NOOP_OPERATIONS_AGENT_TELEMETRY,
  safeAddOperationsTelemetryCounter,
  safeObserveOperationsTelemetryHistogram,
  safeStartOperationsTelemetrySpan,
  type OperationsAgentTelemetry,
  type OperationsTelemetryAttributes,
  type OperationsTelemetryBudgetDimension,
  type OperationsTelemetryCorrelation,
  type OperationsTelemetryMetricLabels,
  type OperationsTelemetryMetricName,
  type OperationsTelemetryOperation,
  type OperationsTelemetryOutcome,
  type OperationsTelemetryOwner,
  type OperationsTelemetryRecoveryMode,
  type OperationsTelemetryRecoveryReason,
  type OperationsTelemetrySpan,
  type OperationsTelemetrySpanKind,
  type OperationsTelemetrySpanName,
} from './internal/operations-telemetry.js';

export {
  InvestigationRepositoryConflictError,
  OwnerReadError,
  type AgentExecutionRuntime,
  type ApplicationEvent,
  type ApplicationOutbox,
  type AuditRecord,
  type AuditRecorder,
  type OperationsAuditDeliveryRecord,
  type OperationsAuditDeliveryRepository,
  type AuthorizationDecision,
  type AuthorizationDecisionReader,
  type BudgetDecision,
  type BudgetGuard,
  type RunResourceBudgetCost,
  type RunResourceBudgetDimension,
  type RunResourceBudgetExhaustion,
  type RunResourceBudgetLimits,
  type RunResourceBudgetOutcome,
  type RunResourceBudgetPolicy,
  type RunResourceBudgetSnapshot,
  type RunResourceBudgetUsage,
  type CheckpointRepository,
  type Clock,
  type CommandCapabilityReadRequest,
  type CommandCapabilityReader,
  type CurrentTelemetryReadRequest,
  type CurrentTelemetryReader,
  type EnergyAnalyticsReadRequest,
  type EnergyAnalyticsReader,
  type GeneratedIdentityKind,
  type IdGenerator,
  type InvestigationAuthorizationAction,
  type InvestigationBusinessRecordRepository,
  type InvestigationCoordinatorPorts,
  type InvestigationRepository,
  type InvestigationRepositoryConflictCode,
  type InvestigationTransaction,
  type InvestigationWriteAuthority,
  type OwnerReadContext,
  type OwnerReadErrorCode,
  type OwnerReadInput,
  type OwnerReadResult,
  type OwnerReaders,
  type ParallelReadBatch,
  type ParallelReadRequest,
  type RegistryReadRequest,
  type RegistryReader,
  type RuntimeCheckpoint,
  type RuntimeCheckpointDraft,
  type RuntimePlanningContext,
  type RuntimePlanningResult,
  type RuntimeReadPlan,
  type ToolAuthorizationGrant,
  type ToolAuthorizationReader,
} from './internal/ports.js';

export const applicationModule = Object.freeze({
  name: 'application',
  layer: 'application',
  dependencies: [domainModule.name],
} as const);

export type ApplicationModule = typeof applicationModule;
