import type {
  BreakdownAnalyticsData,
  BreakdownFilterParams,
  BreakdownSubsystemItem,
  EnergyFlowLink,
  EnergyFlowNode,
  SubmeteringPointRecord,
} from './breakdown-types';

const MOCK_SUBSYSTEMS: readonly BreakdownSubsystemItem[] = [
  {
    id: 'sub-chillers',
    name: '冷水机组群 (CH-01~04)',
    category: 'CHILLER_PLANT',
    categoryLabel: '冷源主机',
    energyKWh: 128900,
    sharePercent: 57.0,
    momPercent: -5.2,
    yoyPercent: -7.8,
    deviceCount: 4,
    meterCount: 4,
    currentPowerKW: 462.5,
    efficiencyMetric: 'COP 5.62',
    color: '#2563eb',
  },
  {
    id: 'sub-chw-pumps',
    name: '冷冻水一次/二次水泵组',
    category: 'CHILLED_WATER_PUMPS',
    categoryLabel: '冷冻输配',
    energyKWh: 27120,
    sharePercent: 12.0,
    momPercent: -3.4,
    yoyPercent: -4.1,
    deviceCount: 6,
    meterCount: 6,
    currentPowerKW: 78.4,
    efficiencyMetric: '输配能效比 0.021',
    color: '#06b6d4',
  },
  {
    id: 'sub-cw-pumps',
    name: '冷却水循环泵组',
    category: 'CONDENSER_WATER_PUMPS',
    categoryLabel: '冷却循环',
    energyKWh: 21940,
    sharePercent: 9.7,
    momPercent: -4.1,
    yoyPercent: -5.3,
    deviceCount: 5,
    meterCount: 5,
    currentPowerKW: 62.0,
    efficiencyMetric: '扬程利用率 88%',
    color: '#0ea5e9',
  },
  {
    id: 'sub-ahu',
    name: '空气处理机组群 (AHU/PAU)',
    category: 'AHU_TERMINALS',
    categoryLabel: '空调末端',
    energyKWh: 24860,
    sharePercent: 11.0,
    momPercent: -2.1,
    yoyPercent: -3.5,
    deviceCount: 16,
    meterCount: 16,
    currentPowerKW: 72.8,
    efficiencyMetric: '风机比功率 0.18 W/(m³/h)',
    color: '#10b981',
  },
  {
    id: 'sub-cooling-towers',
    name: '开式冷却塔风机群 (CT-01~04)',
    category: 'COOLING_TOWERS',
    categoryLabel: '散热系统',
    energyKWh: 13608,
    sharePercent: 6.0,
    momPercent: +1.4,
    yoyPercent: -2.0,
    deviceCount: 8,
    meterCount: 4,
    currentPowerKW: 38.6,
    efficiencyMetric: '逼近度 2.8°C',
    color: '#f59e0b',
  },
  {
    id: 'sub-aux',
    name: '水处理、补水与机房照明动力',
    category: 'AUXILIARY',
    categoryLabel: '动力辅助',
    energyKWh: 9572,
    sharePercent: 4.3,
    momPercent: -0.8,
    yoyPercent: -1.2,
    deviceCount: 12,
    meterCount: 7,
    currentPowerKW: 24.2,
    efficiencyMetric: '机房PUE 1.042',
    color: '#8b5cf6',
  },
];

const MOCK_FLOW_NODES: readonly EnergyFlowNode[] = [
  { id: 'grid-10kv', name: '10kV 市电进线', level: 'SOURCE', energyKWh: 226000, percent: 100, color: '#6366f1' },
  { id: 'trans-t1', name: '1# 动力变压器 (2000kVA)', level: 'TRANSFORM', energyKWh: 156020, percent: 69.0, color: '#3b82f6' },
  { id: 'trans-t2', name: '2# 动力变压器 (1600kVA)', level: 'TRANSFORM', energyKWh: 69980, percent: 31.0, color: '#0ea5e9' },
  { id: 'chiller-group', name: '冷水主机群', level: 'CONSUMER', energyKWh: 128900, percent: 57.0, color: '#2563eb' },
  { id: 'pumps-group', name: '水泵输配系统', level: 'CONSUMER', energyKWh: 49060, percent: 21.7, color: '#06b6d4' },
  { id: 'terminal-group', name: '空气末端系统', level: 'CONSUMER', energyKWh: 24860, percent: 11.0, color: '#10b981' },
  { id: 'towers-group', name: '冷却塔散热系统', level: 'CONSUMER', energyKWh: 13608, percent: 6.0, color: '#f59e0b' },
  { id: 'aux-group', name: '辅助动力', level: 'CONSUMER', energyKWh: 9572, percent: 4.3, color: '#8b5cf6' },
  { id: 'cooling-output', name: '建筑冷负荷产出', level: 'OUTPUT', energyKWh: 724400, percent: 320.5, color: '#059669' },
  { id: 'heat-rejection', name: '冷却塔散热耗散', level: 'OUTPUT', energyKWh: 853300, percent: 377.5, color: '#d97706' },
];

const MOCK_FLOW_LINKS: readonly EnergyFlowLink[] = [
  { source: 'grid-10kv', target: 'trans-t1', valueKWh: 156020, label: '进线配电' },
  { source: 'grid-10kv', target: 'trans-t2', valueKWh: 69980, label: '进线配电' },
  { source: 'trans-t1', target: 'chiller-group', valueKWh: 128900, label: '冷机专线' },
  { source: 'trans-t1', target: 'pumps-group', valueKWh: 27120, label: '泵组回路' },
  { source: 'trans-t2', target: 'pumps-group', valueKWh: 21940, label: '冷却回路' },
  { source: 'trans-t2', target: 'terminal-group', valueKWh: 24860, label: '末端配电' },
  { source: 'trans-t2', target: 'towers-group', valueKWh: 13608, label: '塔区配电' },
  { source: 'trans-t2', target: 'aux-group', valueKWh: 9572, label: '辅助低压' },
  { source: 'chiller-group', target: 'cooling-output', valueKWh: 724400, label: '制冷量' },
  { source: 'towers-group', target: 'heat-rejection', valueKWh: 853300, label: '向环境散热' },
];

const MOCK_SUBMETERS: readonly SubmeteringPointRecord[] = [
  {
    id: 'meter-ch-01',
    meterCode: 'EM-B2-01',
    meterName: '1# 离心冷水主机动力电表',
    systemPath: '冷站系统 > 冷水机组 > 1#离心冷机',
    category: 'CHILLER_PLANT',
    location: 'B2层冷冻机房低压配电柜 AA01',
    todayKWh: 2840,
    monthKWh: 68450,
    currentPowerKW: 245.2,
    powerFactor: 0.94,
    momVariancePercent: -4.8,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-ch-02',
    meterCode: 'EM-B2-02',
    meterName: '2# 螺杆冷水主机动力电表',
    systemPath: '冷站系统 > 冷水机组 > 2#螺杆冷机',
    category: 'CHILLER_PLANT',
    location: 'B2层冷冻机房低压配电柜 AA02',
    todayKWh: 2260,
    monthKWh: 60450,
    currentPowerKW: 198.6,
    powerFactor: 0.93,
    momVariancePercent: -5.6,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-chwp-01',
    meterCode: 'EM-B2-03',
    meterName: '1# 一次冷冻水泵动力电表',
    systemPath: '水力输配 > 冷冻泵组 > CHWP-01',
    category: 'CHILLED_WATER_PUMPS',
    location: 'B2层变频配电柜 BB01',
    todayKWh: 485,
    monthKWh: 13860,
    currentPowerKW: 38.5,
    powerFactor: 0.91,
    momVariancePercent: -3.2,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-chwp-02',
    meterCode: 'EM-B2-04',
    meterName: '2# 一次冷冻水泵动力电表',
    systemPath: '水力输配 > 冷冻泵组 > CHWP-02',
    category: 'CHILLED_WATER_PUMPS',
    location: 'B2层变频配电柜 BB02',
    todayKWh: 462,
    monthKWh: 13260,
    currentPowerKW: 39.9,
    powerFactor: 0.92,
    momVariancePercent: -3.6,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-cwp-01',
    meterCode: 'EM-B2-05',
    meterName: '1# 冷却循环水泵动力电表',
    systemPath: '散热循环 > 冷却泵组 > CWP-01',
    category: 'CONDENSER_WATER_PUMPS',
    location: 'B2层机房配电柜 CC01',
    todayKWh: 410,
    monthKWh: 11200,
    currentPowerKW: 32.4,
    powerFactor: 0.90,
    momVariancePercent: -4.0,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-cwp-02',
    meterCode: 'EM-B2-06',
    meterName: '2# 冷却循环水泵动力电表',
    systemPath: '散热循环 > 冷却泵组 > CWP-02',
    category: 'CONDENSER_WATER_PUMPS',
    location: 'B2层机房配电柜 CC02',
    todayKWh: 395,
    monthKWh: 10740,
    currentPowerKW: 29.6,
    powerFactor: 0.89,
    momVariancePercent: -4.2,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-ct-01',
    meterCode: 'EM-RF-01',
    meterName: '1#~2# 冷却塔风机总表',
    systemPath: '散热系统 > 冷却塔群 > CT-01/02',
    category: 'COOLING_TOWERS',
    location: '主楼屋面冷却塔动力箱 RFA01',
    todayKWh: 245,
    monthKWh: 6920,
    currentPowerKW: 19.8,
    powerFactor: 0.88,
    momVariancePercent: +1.2,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-ct-02',
    meterCode: 'EM-RF-02',
    meterName: '3#~4# 冷却塔风机总表',
    systemPath: '散热系统 > 冷却塔群 > CT-03/04',
    category: 'COOLING_TOWERS',
    location: '主楼屋面冷却塔动力箱 RFA02',
    todayKWh: 236,
    monthKWh: 6688,
    currentPowerKW: 18.8,
    powerFactor: 0.87,
    momVariancePercent: +1.6,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-ahu-f1',
    meterCode: 'EM-F1-01',
    meterName: '1F 商场东区 AHU-01~04 空调箱电表',
    systemPath: '空调末端 > 一层商场 > AHU-E01~04',
    category: 'AHU_TERMINALS',
    location: '1F 电气管井配电箱 AP-1F-E',
    todayKWh: 320,
    monthKWh: 8250,
    currentPowerKW: 24.5,
    powerFactor: 0.91,
    momVariancePercent: -2.3,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-ahu-f2',
    meterCode: 'EM-F2-01',
    meterName: '2F 商场中庭 AHU-05~08 空调箱电表',
    systemPath: '空调末端 > 二层中庭 > AHU-C05~08',
    category: 'AHU_TERMINALS',
    location: '2F 电气管井配电箱 AP-2F-C',
    todayKWh: 312,
    monthKWh: 7980,
    currentPowerKW: 23.8,
    powerFactor: 0.90,
    momVariancePercent: -1.9,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-pau-f3',
    meterCode: 'EM-F3-01',
    meterName: '3F 餐饮区 PAU 新风机组动力电表',
    systemPath: '空调末端 > 三层餐饮 > PAU-01~04',
    category: 'AHU_TERMINALS',
    location: '3F 电气管井配电箱 AP-3F-F',
    todayKWh: 334,
    monthKWh: 8630,
    currentPowerKW: 24.5,
    powerFactor: 0.92,
    momVariancePercent: -2.1,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
  {
    id: 'meter-aux-01',
    meterCode: 'EM-B2-AUX',
    meterName: 'B2 机房定压补水与加药软水系统电表',
    systemPath: '动力辅助 > 水处理系统 > 补水定压',
    category: 'AUXILIARY',
    location: 'B2层机房辅助配电箱 AP-B2-AUX',
    todayKWh: 110,
    monthKWh: 3120,
    currentPowerKW: 8.4,
    powerFactor: 0.86,
    momVariancePercent: -0.6,
    healthStatus: 'ONLINE',
    lastActiveTime: '刚刚 (0秒前)',
  },
];

export const breakdownService = {
  getBreakdownAnalytics: async (
    params?: BreakdownFilterParams
  ): Promise<BreakdownAnalyticsData> => {
    // Brief network latency
    await new Promise((resolve) => setTimeout(resolve, 80));

    let filteredSubmeters = [...MOCK_SUBMETERS];
    if (params?.category && params.category !== 'ALL') {
      filteredSubmeters = filteredSubmeters.filter(
        (m) => m.category === params.category
      );
    }
    if (params?.search) {
      const q = params.search.toLowerCase();
      filteredSubmeters = filteredSubmeters.filter(
        (m) =>
          m.meterName.toLowerCase().includes(q) ||
          m.meterCode.toLowerCase().includes(q) ||
          m.systemPath.toLowerCase().includes(q) ||
          m.location.toLowerCase().includes(q)
      );
    }

    return {
      summary: {
        totalEnergyKWh: 226000,
        chillerSharePercent: 57.0,
        pumpingSharePercent: 21.7,
        terminalSharePercent: 11.0,
        coolingTowerSharePercent: 6.0,
        systemCop: 5.42,
        pumpingEfficiency: 0.038,
        activeMeterCount: 42,
        totalMeterCount: 42,
      },
      subsystems: MOCK_SUBSYSTEMS,
      flowNodes: MOCK_FLOW_NODES,
      flowLinks: MOCK_FLOW_LINKS,
      submeters: filteredSubmeters,
      periodLabel: '2026年9月 (本计费周期)',
    };
  },
};
