// Generated by scripts/generate-operations-agent-control-contracts.mjs. Do not edit.

export const OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTEXT_ID = "https://hvac.local/contracts/operations-agent/trusted-runtime-context/v1" as const;

export const OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTEXT_KEYS = [
  "schemaVersion",
  "source",
  "trust",
  "investigationId",
  "scope",
  "revision",
  "runId",
  "runStatus",
  "runtimeRevision",
  "allowedReadTools",
  "effectPolicy",
  "scopePolicy",
  "untrustedContentPolicy",
] as const;

export const OPERATIONS_AGENT_TRUSTED_RUNTIME_SCOPE_KEYS = [
  "tenantId",
  "siteId",
  "equipmentId",
  "deviceId",
] as const;

export const OPERATIONS_AGENT_TRUSTED_RUNTIME_MAXIMUM_IDENTITY_CHARACTERS = 256 as const;

export const OPERATIONS_AGENT_TRUSTED_RUNTIME_CONTROL_POLICY = Object.freeze({
  schemaVersion: 1,
  source: "APPLICATION_POLICY",
  trust: "TRUSTED_CONTROL",
  runStatus: "ACTIVE",
  effectPolicy: "READ_ONLY",
  scopePolicy: "EXACT_INVESTIGATION_SCOPE",
  untrustedContentPolicy: "EXCLUDED",
} as const);
