import type {
  ChillerUnitTelemetry,
  ControlLoopItem,
  PumpUnitTelemetry,
  RealtimeAnalyticsData,
  RealtimeFilterParams,
  SystemOperatingSummary,
  TowerUnitTelemetry,
} from './realtime-types';

export const realtimeService = {
  async getRealtimeOperations(
    _params?: RealtimeFilterParams
  ): Promise<RealtimeAnalyticsData> {
    const summary: SystemOperatingSummary = {
      systemMode: 'AI全局寻优闭环',
      optimizationStatus: 'ACTIVE',
      totalCoolingCapacityKW: 3420,
      coolingLoadPercent: 74.2,
      instantCop: 5.28,
      instantPowerKW: 647.7,
      chwSupplyTemp: 7.2,
      chwReturnTemp: 12.4,
      chwSetpointTemp: 7.0,
      cwSupplyTemp: 26.8,
      cwReturnTemp: 31.6,
      cwApproachTemp: 2.8,
      systemDeltaPMPa: 0.22,
      systemDeltaPSetpoint: 0.21,
      activeFaultCount: 0,
    };

    const chillers: readonly ChillerUnitTelemetry[] = [
      {
        id: 'CH-01',
        name: '1# 双级变频离心冷水机组',
        type: 'CENTRIFUGAL',
        status: 'RUNNING',
        loadPercent: 78.5,
        powerKW: 295.4,
        currentA: 448.2,
        cop: 5.82,
        chwSupplyTemp: 7.1,
        chwReturnTemp: 12.5,
        cwSupplyTemp: 26.8,
        cwReturnTemp: 31.7,
        evapPressureKPa: 342.5,
        condPressureKPa: 890.2,
        oilPressureKPa: 520.1,
        oilTempC: 54.2,
        runningHours: 12450,
      },
      {
        id: 'CH-02',
        name: '2# 磁悬浮离心冷水机组',
        type: 'MAGLEV',
        status: 'RUNNING',
        loadPercent: 69.8,
        powerKW: 242.8,
        currentA: 368.5,
        cop: 6.15,
        chwSupplyTemp: 7.2,
        chwReturnTemp: 12.3,
        cwSupplyTemp: 26.8,
        cwReturnTemp: 31.5,
        evapPressureKPa: 345.0,
        condPressureKPa: 885.6,
        oilPressureKPa: 0, // 无油磁轴承
        oilTempC: 38.5,
        runningHours: 8920,
      },
      {
        id: 'CH-03',
        name: '3# 离心冷水机组 (热备用)',
        type: 'CENTRIFUGAL',
        status: 'STANDBY',
        loadPercent: 0,
        powerKW: 0,
        currentA: 0,
        cop: 0,
        chwSupplyTemp: 12.4,
        chwReturnTemp: 12.4,
        cwSupplyTemp: 26.8,
        cwReturnTemp: 26.8,
        evapPressureKPa: 420.0,
        condPressureKPa: 780.0,
        oilPressureKPa: 480.0,
        oilTempC: 28.0,
        runningHours: 14100,
      },
    ];

    const chwPumps: readonly PumpUnitTelemetry[] = [
      {
        id: 'CHWP-01',
        name: '1# 冷冻水一次泵',
        loop: 'CHW',
        status: 'RUNNING',
        frequencyHz: 43.5,
        powerKW: 38.2,
        currentA: 68.4,
        flowM3H: 320,
        headM: 28.5,
        runningHours: 9800,
      },
      {
        id: 'CHWP-02',
        name: '2# 冷冻水一次泵',
        loop: 'CHW',
        status: 'RUNNING',
        frequencyHz: 42.0,
        powerKW: 35.8,
        currentA: 64.2,
        flowM3H: 305,
        headM: 27.8,
        runningHours: 9400,
      },
      {
        id: 'CHWP-03',
        name: '3# 冷冻水一次泵 (备用)',
        loop: 'CHW',
        status: 'STANDBY',
        frequencyHz: 0,
        powerKW: 0,
        currentA: 0,
        flowM3H: 0,
        headM: 0,
        runningHours: 8200,
      },
    ];

    const cwPumps: readonly PumpUnitTelemetry[] = [
      {
        id: 'CWP-01',
        name: '1# 冷却水循环泵',
        loop: 'CW',
        status: 'RUNNING',
        frequencyHz: 46.2,
        powerKW: 44.5,
        currentA: 78.5,
        flowM3H: 380,
        headM: 26.2,
        runningHours: 10200,
      },
      {
        id: 'CWP-02',
        name: '2# 冷却水循环泵',
        loop: 'CW',
        status: 'RUNNING',
        frequencyHz: 45.0,
        powerKW: 42.1,
        currentA: 74.3,
        flowM3H: 365,
        headM: 25.8,
        runningHours: 9950,
      },
      {
        id: 'CWP-03',
        name: '3# 冷却水循环泵 (备用)',
        loop: 'CW',
        status: 'STANDBY',
        frequencyHz: 0,
        powerKW: 0,
        currentA: 0,
        flowM3H: 0,
        headM: 0,
        runningHours: 8800,
      },
    ];

    const towers: readonly TowerUnitTelemetry[] = [
      {
        id: 'CT-01',
        name: '1# 开式超静音冷却塔',
        status: 'RUNNING',
        fanSpeedPercent: 82.0,
        frequencyHz: 41.0,
        powerKW: 15.2,
        currentA: 28.5,
        inletTemp: 31.6,
        outletTemp: 26.8,
        runningHours: 11200,
      },
      {
        id: 'CT-02',
        name: '2# 开式超静音冷却塔',
        status: 'RUNNING',
        fanSpeedPercent: 78.5,
        frequencyHz: 39.2,
        powerKW: 13.8,
        currentA: 26.2,
        inletTemp: 31.6,
        outletTemp: 26.8,
        runningHours: 10900,
      },
      {
        id: 'CT-03',
        name: '3# 开式超静音冷却塔 (待机)',
        status: 'STANDBY',
        fanSpeedPercent: 0,
        frequencyHz: 0,
        powerKW: 0,
        currentA: 0,
        inletTemp: 26.8,
        outletTemp: 26.8,
        runningHours: 9600,
      },
    ];

    const controlLoops: readonly ControlLoopItem[] = [
      {
        id: 'LOOP-01',
        name: '冷冻水供水温度自适应重置回路',
        loopTag: 'TIC-CHW-01',
        variableName: '冷冻水供水温度',
        setpoint: 7.0,
        actualValue: 7.2,
        deviation: 0.2,
        unit: '°C',
        outputPercent: 78.5,
        mode: 'AUTO',
        status: 'STABLE',
      },
      {
        id: 'LOOP-02',
        name: '末端最不利环路最优化压差控制',
        loopTag: 'PIC-DIFF-01',
        variableName: '系统最不利供回水压差',
        setpoint: 0.21,
        actualValue: 0.22,
        deviation: 0.01,
        unit: 'MPa',
        outputPercent: 84.0,
        mode: 'AUTO',
        status: 'STABLE',
      },
      {
        id: 'LOOP-03',
        name: '冷却水最佳逼近度变频节能控制',
        loopTag: 'TIC-CW-01',
        variableName: '冷却塔出水温度 (逼近度)',
        setpoint: 26.5,
        actualValue: 26.8,
        deviation: 0.3,
        unit: '°C',
        outputPercent: 80.2,
        mode: 'AUTO',
        status: 'STABLE',
      },
      {
        id: 'LOOP-04',
        name: '冷冻水定压旁通保护回路',
        loopTag: 'FIC-BYPASS-01',
        variableName: '旁通调节阀开度',
        setpoint: 0.0,
        actualValue: 12.0,
        deviation: 12.0,
        unit: '%',
        outputPercent: 12.0,
        mode: 'CASCADE',
        status: 'TRACKING',
      },
    ];

    return {
      summary,
      chillers,
      chwPumps,
      cwPumps,
      towers,
      controlLoops,
      bypassValveOpeningPercent: 12.0,
      updatedAt: new Date().toLocaleTimeString('zh-CN', { hour12: false }),
    };
  },
};
