export {
  OperationsInvestigation,
  OperationsInvestigationError,
  createIdempotencyKey,
  createInvestigationRevision,
  createStepIdentity,
  type AcceptOperatorInput,
  type AcceptOperatorInputResult,
  type AgentRunLeaseView,
  type AgentRunStatus,
  type AgentRunView,
  type AssertAgentRunAuthority,
  type CancelInvestigation,
  type CommitEffectResult,
  type CommitInvestigationEffect,
  type CommittedEffectKind,
  type CommittedEffectView,
  type CreateOperationsInvestigation,
  type EndAgentRun,
  type IdempotencyKey,
  type InvestigationRevision,
  type InvestigationScope,
  type InvestigationStatus,
  type OperationsInvestigationErrorCode,
  type OperationsInvestigationSnapshot,
  type OperationsInvestigationView,
  type OperatorInputAcceptanceView,
  type OperatorInputAnalysisScope,
  type OperatorInputRequestKind,
  type OperatorInputRequestView,
  type OperatorInputSelectField,
  type OperatorInputTextField,
  type PauseAgentRun,
  type ReopenCompletedInvestigation,
  type RequestOperatorInput,
  type ResumeAgentRun,
  type StartAgentRun,
  type StepIdentity,
} from './internal/operations-investigation.js';

export {
  InvestigationBusinessRecordError,
  businessRecordsEqual,
  createInvestigationBusinessRecord,
  type AnalysisReferenceRecord,
  type EvidenceClassification,
  type EvidenceOwner,
  type EvidenceQuality,
  type EvidenceQualityClassification,
  type EvidenceRecord,
  type EvidenceSourceReference,
  type EvidenceWatermark,
  type FindingConclusion,
  type FindingRecord,
  type FindingRequiredNext,
  type FindingRequiredNextPeriod,
  type InvestigationBusinessRecord,
  type InvestigationBusinessRecordErrorCode,
  type InvestigationBusinessRecordType,
  type LogicalTool,
  type OperatorInputAcceptedProvenance,
  type OperatorInputAcceptedRecord,
  type OperatorInputAcceptedValues,
  type ToolExecutionReceiptRecord,
  type ToolExecutionResultCategory,
  type ToolOwner,
  type ToolReceiptMetadataValue,
} from './internal/business-records.js';

export const domainModule = Object.freeze({
  name: 'domain',
  layer: 'domain',
  dependencies: [],
} as const);

export type DomainModule = typeof domainModule;
