// Code generated by scripts/generate-platform-contracts.mjs; DO NOT EDIT.
// Generator: platform-contracts@1.0.0; Contract SHA-256: 68f399f05ec1f72daf56e11cbdd603f45bd03c8e7befc814e5f5a261ac747746

package platformapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	GetHealthPath  = "/api/v1/health"
	GetVersionPath = "/api/v1/version"
)

type BuildInfo struct {
	Service string `json:"service"`
	Version string `json:"version"`
	Commit  string `json:"commit"`
	BuiltAt string `json:"builtAt"`
}

type HealthResponse struct {
	Status    string     `json:"status"`
	Service   string     `json:"service"`
	CheckedAt string     `json:"checkedAt"`
	Build     *BuildInfo `json:"build,omitempty"`
}

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type ProblemDetails struct {
	Type        string       `json:"type"`
	Title       string       `json:"title"`
	Status      int          `json:"status"`
	Detail      string       `json:"detail"`
	Instance    string       `json:"instance"`
	Code        string       `json:"code"`
	TraceID     string       `json:"traceId"`
	Retryable   bool         `json:"retryable"`
	FieldErrors []FieldError `json:"fieldErrors,omitempty"`
}

type GetHealthParams struct {
	IncludeBuild *bool
}

// ServerInterface is the generated HTTP seam implemented by the edge service.
type ServerInterface interface {
	GetHealth(http.ResponseWriter, *http.Request, GetHealthParams)
	GetVersion(http.ResponseWriter, *http.Request)
}

type HTTPClient interface {
	Do(*http.Request) (*http.Response, error)
}

type Client struct {
	baseURL    string
	httpClient HTTPClient
}

func NewClient(baseURL string, httpClient HTTPClient) (*Client, error) {
	if _, err := url.ParseRequestURI(baseURL); err != nil {
		return nil, fmt.Errorf("parse platform Gateway base URL: %w", err)
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient}, nil
}

type Response[T any] struct {
	Data         *T
	Problem      *ProblemDetails
	StatusCode   int
	RequestID    string
	Traceparent  string
	HTTPResponse *http.Response
}

func (c *Client) GetHealth(ctx context.Context, params *GetHealthParams) (*Response[HealthResponse], error) {
	endpoint, err := url.Parse(c.baseURL + GetHealthPath)
	if err != nil {
		return nil, fmt.Errorf("build getHealth URL: %w", err)
	}
	if params != nil && params.IncludeBuild != nil {
		query := endpoint.Query()
		query.Set("includeBuild", fmt.Sprintf("%t", *params.IncludeBuild))
		endpoint.RawQuery = query.Encode()
	}
	return doJSON[HealthResponse](ctx, c.httpClient, http.MethodGet, endpoint.String())
}

func (c *Client) GetVersion(ctx context.Context) (*Response[BuildInfo], error) {
	return doJSON[BuildInfo](ctx, c.httpClient, http.MethodGet, c.baseURL+GetVersionPath)
}

func doJSON[T any](ctx context.Context, client HTTPClient, method, endpoint string) (*Response[T], error) {
	req, err := http.NewRequestWithContext(ctx, method, endpoint, bytes.NewReader(nil))
	if err != nil {
		return nil, fmt.Errorf("create platform Gateway request: %w", err)
	}
	req.Header.Set("Accept", "application/json, application/problem+json")
	httpResponse, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("call platform Gateway: %w", err)
	}
	body, err := io.ReadAll(io.LimitReader(httpResponse.Body, 1<<20))
	if closeErr := httpResponse.Body.Close(); err == nil && closeErr != nil {
		err = closeErr
	}
	if err != nil {
		return nil, fmt.Errorf("read platform Gateway response: %w", err)
	}
	response := &Response[T]{
		StatusCode:   httpResponse.StatusCode,
		RequestID:    httpResponse.Header.Get("X-Request-ID"),
		Traceparent:  httpResponse.Header.Get("traceparent"),
		HTTPResponse: httpResponse,
	}
	if httpResponse.StatusCode >= 200 && httpResponse.StatusCode < 300 {
		var data T
		if err := json.Unmarshal(body, &data); err != nil {
			return nil, fmt.Errorf("decode platform Gateway success response: %w", err)
		}
		response.Data = &data
		return response, nil
	}
	var problem ProblemDetails
	if err := json.Unmarshal(body, &problem); err != nil {
		return nil, fmt.Errorf("decode platform Gateway problem response: %w", err)
	}
	response.Problem = &problem
	return response, nil
}
