// Code generated by scripts/generate-platform-contracts.mjs; DO NOT EDIT.
// Generator: platform-contracts@4.0.0; Contract SHA-256: 9713d98d0157d80c5a1412302ecca57a19f603977ded6f1875f2782c3a7445e5

package platformapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	GetHealthPath                    = "/api/v1/health"
	GetVersionPath                   = "/api/v1/version"
	GetPlatformStatusPath            = "/api/v1/platform/status"
	BeginLoginPath                   = "/api/v1/auth/login"
	CompleteLoginPath                = "/api/v1/auth/callback"
	GetCurrentPrincipalPath          = "/api/v1/principal"
	LogoutPath                       = "/api/v1/auth/logout"
	RevokeSessionPathTemplate        = "/api/v1/auth/sessions/{sessionId}/revoke"
	GetSessionAuditEventPathTemplate = "/api/v1/audit/session-events/{messageId}"
)

type BuildInfo struct {
	Service string `json:"service"`
	Version string `json:"version"`
	Commit  string `json:"commit"`
	BuiltAt string `json:"builtAt"`
}

type HealthResponse struct {
	Status    string     `json:"status"`
	Service   string     `json:"service"`
	CheckedAt string     `json:"checkedAt"`
	Build     *BuildInfo `json:"build,omitempty"`
}

type PlatformStatusResponse struct {
	Status              string `json:"status"`
	Service             string `json:"service"`
	Implementation      string `json:"implementation"`
	Version             string `json:"version"`
	CheckedAt           string `json:"checkedAt"`
	RoutePolicyRevision int64  `json:"routePolicyRevision"`
	RouteRevision       int64  `json:"routeRevision"`
	CompatibilityMode   string `json:"compatibilityMode"`
}

type UserPrincipal struct {
	Subject     string   `json:"subject"`
	Issuer      string   `json:"issuer"`
	DisplayName string   `json:"displayName"`
	Email       string   `json:"email"`
	Roles       []string `json:"roles"`
}

type ServicePrincipal struct {
	Service  string `json:"service"`
	SPIFFEID string `json:"spiffeId"`
}

type PrincipalContext struct {
	InitiatingPrincipal       UserPrincipal    `json:"initiatingPrincipal"`
	ExecutingServicePrincipal ServicePrincipal `json:"executingServicePrincipal"`
	ActingOrganizationID      string           `json:"actingOrganizationId"`
	Audience                  string           `json:"audience"`
	PolicyRevision            string           `json:"policyRevision"`
	DelegationExpiresAt       string           `json:"delegationExpiresAt"`
}

type SessionView struct {
	ID                    string `json:"id"`
	ExpiresAt             string `json:"expiresAt"`
	CSRFToken             string `json:"csrfToken"`
	RevocationObjectiveMS int    `json:"revocationObjectiveMs"`
	LastAuditMessageID    string `json:"lastAuditMessageId"`
}

type CurrentPrincipalResponse struct {
	Principal UserPrincipal    `json:"principal"`
	Context   PrincipalContext `json:"context"`
	Session   SessionView      `json:"session"`
}

type SessionRevocationResponse struct {
	SessionID      string `json:"sessionId"`
	RevokedAt      string `json:"revokedAt"`
	ObjectiveMS    int    `json:"objectiveMs"`
	AuditMessageID string `json:"auditMessageId"`
}

type AuditRecord struct {
	LedgerSequence       int64  `json:"ledgerSequence"`
	MessageID            string `json:"messageId"`
	SchemaVersion        uint32 `json:"schemaVersion"`
	OrganizationID       string `json:"organizationId"`
	AggregateType        string `json:"aggregateType"`
	AggregateID          string `json:"aggregateId"`
	AggregateVersion     uint64 `json:"aggregateVersion"`
	OccurredAt           string `json:"occurredAt"`
	InitiatingSubject    string `json:"initiatingSubject"`
	InitiatingIssuer     string `json:"initiatingIssuer"`
	ExecutingService     string `json:"executingService"`
	ExecutingSPIFFEID    string `json:"executingSpiffeId"`
	ActingOrganizationID string `json:"actingOrganizationId"`
	Action               string `json:"action"`
	Result               string `json:"result"`
	PolicyRevision       string `json:"policyRevision"`
	CorrelationID        string `json:"correlationId"`
	CausationID          string `json:"causationId"`
	TraceID              string `json:"traceId"`
	PayloadSHA256        string `json:"payloadSha256"`
	PreviousRecordHash   string `json:"previousRecordHash"`
	RecordHash           string `json:"recordHash"`
	RecordedAt           string `json:"recordedAt"`
}

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type ProblemDetails struct {
	Type        string       `json:"type"`
	Title       string       `json:"title"`
	Status      int          `json:"status"`
	Detail      string       `json:"detail"`
	Instance    string       `json:"instance"`
	Code        string       `json:"code"`
	TraceID     string       `json:"traceId"`
	Retryable   bool         `json:"retryable"`
	FieldErrors []FieldError `json:"fieldErrors,omitempty"`
}

type GetHealthParams struct{ IncludeBuild *bool }
type BeginLoginParams struct {
	ReturnTo  string
	LoginHint string
}
type CompleteLoginParams struct {
	Code  string
	State string
}
type LogoutParams struct{ CSRFToken string }
type RevokeSessionParams struct {
	SessionID string
	CSRFToken string
}
type GetSessionAuditEventParams struct{ MessageID string }

type ServerInterface interface {
	GetHealth(http.ResponseWriter, *http.Request, GetHealthParams)
	GetVersion(http.ResponseWriter, *http.Request)
	GetPlatformStatus(http.ResponseWriter, *http.Request)
	BeginLogin(http.ResponseWriter, *http.Request, BeginLoginParams)
	CompleteLogin(http.ResponseWriter, *http.Request, CompleteLoginParams)
	GetCurrentPrincipal(http.ResponseWriter, *http.Request)
	Logout(http.ResponseWriter, *http.Request, LogoutParams)
	RevokeSession(http.ResponseWriter, *http.Request, RevokeSessionParams)
	GetSessionAuditEvent(http.ResponseWriter, *http.Request, GetSessionAuditEventParams)
}

type HTTPClient interface {
	Do(*http.Request) (*http.Response, error)
}

type Client struct {
	baseURL    string
	httpClient HTTPClient
}

func NewClient(baseURL string, httpClient HTTPClient) (*Client, error) {
	if _, err := url.ParseRequestURI(baseURL); err != nil {
		return nil, fmt.Errorf("parse platform Gateway base URL: %w", err)
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient}, nil
}

type Response[T any] struct {
	Data                *T
	Problem             *ProblemDetails
	StatusCode          int
	RequestID           string
	Traceparent         string
	AuditMessageID      string
	RoutePolicyRevision string
	HTTPResponse        *http.Response
}

func (c *Client) GetHealth(ctx context.Context, params *GetHealthParams) (*Response[HealthResponse], error) {
	endpoint, err := url.Parse(c.baseURL + GetHealthPath)
	if err != nil {
		return nil, err
	}
	if params != nil && params.IncludeBuild != nil {
		query := endpoint.Query()
		query.Set("includeBuild", fmt.Sprintf("%t", *params.IncludeBuild))
		endpoint.RawQuery = query.Encode()
	}
	return doJSON[HealthResponse](ctx, c.httpClient, http.MethodGet, endpoint.String(), "", nil)
}

func (c *Client) GetVersion(ctx context.Context) (*Response[BuildInfo], error) {
	return doJSON[BuildInfo](ctx, c.httpClient, http.MethodGet, c.baseURL+GetVersionPath, "", nil)
}

func (c *Client) GetPlatformStatus(ctx context.Context) (*Response[PlatformStatusResponse], error) {
	return doJSON[PlatformStatusResponse](ctx, c.httpClient, http.MethodGet, c.baseURL+GetPlatformStatusPath, "", nil)
}

func (c *Client) GetCurrentPrincipal(ctx context.Context) (*Response[CurrentPrincipalResponse], error) {
	return doJSON[CurrentPrincipalResponse](ctx, c.httpClient, http.MethodGet, c.baseURL+GetCurrentPrincipalPath, "", nil)
}

func (c *Client) Logout(ctx context.Context, csrfToken string) (*Response[struct{}], error) {
	return doJSON[struct{}](ctx, c.httpClient, http.MethodPost, c.baseURL+LogoutPath, csrfToken, nil)
}

func (c *Client) RevokeSession(ctx context.Context, sessionID, csrfToken string) (*Response[SessionRevocationResponse], error) {
	path := strings.Replace(RevokeSessionPathTemplate, "{sessionId}", url.PathEscape(sessionID), 1)
	return doJSON[SessionRevocationResponse](ctx, c.httpClient, http.MethodPost, c.baseURL+path, csrfToken, nil)
}

func (c *Client) GetSessionAuditEvent(ctx context.Context, messageID string) (*Response[AuditRecord], error) {
	path := strings.Replace(GetSessionAuditEventPathTemplate, "{messageId}", url.PathEscape(messageID), 1)
	return doJSON[AuditRecord](ctx, c.httpClient, http.MethodGet, c.baseURL+path, "", nil)
}

func doJSON[T any](ctx context.Context, client HTTPClient, method, endpoint, csrfToken string, body []byte) (*Response[T], error) {
	req, err := http.NewRequestWithContext(ctx, method, endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json, application/problem+json")
	if csrfToken != "" {
		req.Header.Set("X-CSRF-Token", csrfToken)
	}
	httpResponse, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("call platform Gateway: %w", err)
	}
	payload, err := io.ReadAll(io.LimitReader(httpResponse.Body, 1<<20))
	_ = httpResponse.Body.Close()
	if err != nil {
		return nil, err
	}
	response := &Response[T]{StatusCode: httpResponse.StatusCode, RequestID: httpResponse.Header.Get("X-Request-ID"), Traceparent: httpResponse.Header.Get("traceparent"), AuditMessageID: httpResponse.Header.Get("X-Audit-Message-ID"), RoutePolicyRevision: httpResponse.Header.Get("X-Route-Policy-Revision"), HTTPResponse: httpResponse}
	if httpResponse.StatusCode >= 200 && httpResponse.StatusCode < 300 {
		if httpResponse.StatusCode == http.StatusNoContent {
			var zero T
			response.Data = &zero
			return response, nil
		}
		var data T
		if err := json.Unmarshal(payload, &data); err != nil {
			return nil, fmt.Errorf("decode platform Gateway success response: %w", err)
		}
		response.Data = &data
		return response, nil
	}
	var problem ProblemDetails
	if err := json.Unmarshal(payload, &problem); err != nil {
		return nil, fmt.Errorf("decode platform Gateway problem response: %w", err)
	}
	response.Problem = &problem
	return response, nil
}
