// Code generated by scripts/generate-s2-telemetry-contracts.mjs; DO NOT EDIT.
// OpenAPI SHA-256: 3957029ac17e52d83ee7c9dfe8458c01ce22daee78ec6b584ad622149a57ff3d; Publication SHA-256: 97b856dfbc1ec9b9e48203580d94ef5ba2b460fc20bdd58786aab306b2a59a56; Generator: s2-telemetry-contracts@1.0.0 // gitleaks:allow

package s2telemetryapi

import (
	"encoding/json"
	"fmt"
	"net/http"
)

const (
	OpenAPIContractSHA256     = "3957029ac17e52d83ee7c9dfe8458c01ce22daee78ec6b584ad622149a57ff3d" // gitleaks:allow
	PublicationContractSHA256 = "97b856dfbc1ec9b9e48203580d94ef5ba2b460fc20bdd58786aab306b2a59a56" // gitleaks:allow
)

type OperationDescriptor struct {
	OperationID string
	Method      string
	Path        string
}

var Operations = [...]OperationDescriptor{
	{OperationID: "getDeviceObservationSnapshot", Method: "GET", Path: "/api/v1/devices/{deviceId}/observation-snapshot"},
	{OperationID: "batchGetDeviceObservationSnapshots", Method: "POST", Path: "/api/v1/telemetry/observation-snapshots:batchGet"},
	{OperationID: "bootstrapTelemetrySubscriptions", Method: "POST", Path: "/api/v1/telemetry/subscriptions:bootstrap"},
	{OperationID: "checkpointTelemetryRecoveryCursors", Method: "POST", Path: "/api/v1/telemetry/recovery-cursors:checkpoint"},
	{OperationID: "queryDeviceHistory", Method: "POST", Path: "/api/v1/telemetry/device-series:query"},
	{OperationID: "queryDeviceHistoryAggregate", Method: "POST", Path: "/api/v1/telemetry/device-series:aggregate"},
}

const (
	GetDeviceObservationSnapshotPathTemplate = "/api/v1/devices/{deviceId}/observation-snapshot"
	BatchGetDeviceObservationSnapshotsPath   = "/api/v1/telemetry/observation-snapshots:batchGet"
	BootstrapTelemetrySubscriptionsPath      = "/api/v1/telemetry/subscriptions:bootstrap"
	CheckpointTelemetryRecoveryCursorsPath   = "/api/v1/telemetry/recovery-cursors:checkpoint"
	QueryDeviceHistoryPath                   = "/api/v1/telemetry/device-series:query"
	QueryDeviceHistoryAggregatePath          = "/api/v1/telemetry/device-series:aggregate"
)

type GetDeviceObservationSnapshotParams struct {
	Keys []TelemetryKey
}

type ServerInterface interface {
	GetDeviceObservationSnapshot(http.ResponseWriter, *http.Request, string, GetDeviceObservationSnapshotParams)
	BatchGetDeviceObservationSnapshots(http.ResponseWriter, *http.Request, BatchGetObservationSnapshotsRequest)
	BootstrapTelemetrySubscriptions(http.ResponseWriter, *http.Request, SubscriptionBootstrapRequest)
	CheckpointTelemetryRecoveryCursors(http.ResponseWriter, *http.Request, RecoveryCursorCheckpointRequest)
	QueryDeviceHistory(http.ResponseWriter, *http.Request, DeviceHistoryRequest)
	QueryDeviceHistoryAggregate(http.ResponseWriter, *http.Request, DeviceHistoryAggregateRequest)
}

type GetDeviceObservationSnapshotResponse = DeviceObservationSnapshot
type BatchGetDeviceObservationSnapshotsRequest = BatchGetObservationSnapshotsRequest
type BatchGetDeviceObservationSnapshotsResponse = BatchGetObservationSnapshotsResponse
type BootstrapTelemetrySubscriptionsRequest = SubscriptionBootstrapRequest
type BootstrapTelemetrySubscriptionsResponse = SubscriptionBootstrapResponse
type CheckpointTelemetryRecoveryCursorsRequest = RecoveryCursorCheckpointRequest
type CheckpointTelemetryRecoveryCursorsResponse = RecoveryCursorCheckpointResponse
type QueryDeviceHistoryRequest = DeviceHistoryRequest
type QueryDeviceHistoryResponse = DeviceHistoryResponse
type QueryDeviceHistoryAggregateRequest = DeviceHistoryAggregateRequest
type QueryDeviceHistoryAggregateResponse = DeviceHistoryAggregateResponse

type UUIDv7 string

type Instant string

type BusinessRevision int64

type PolicyRevision int64

type TelemetryKey string

type ClientSubscriptionId string

type OpaqueSubscriptionId string

type OpaqueChannel string

type OpaqueRecoveryCursor string

type EvaluationAvailability string

const (
	EvaluationAvailabilityAvailable   EvaluationAvailability = "AVAILABLE"
	EvaluationAvailabilityUnavailable EvaluationAvailability = "UNAVAILABLE"
)

type PresenceApplicability string

const (
	PresenceApplicabilityApplicable    PresenceApplicability = "APPLICABLE"
	PresenceApplicabilityNotApplicable PresenceApplicability = "NOT_APPLICABLE"
)

type DevicePresenceState string

const (
	DevicePresenceStateOnline  DevicePresenceState = "ONLINE"
	DevicePresenceStateOffline DevicePresenceState = "OFFLINE"
	DevicePresenceStateUnknown DevicePresenceState = "UNKNOWN"
)

type TelemetryFreshness string

const (
	TelemetryFreshnessFresh   TelemetryFreshness = "FRESH"
	TelemetryFreshnessStale   TelemetryFreshness = "STALE"
	TelemetryFreshnessMissing TelemetryFreshness = "MISSING"
)

type TelemetryQuality string

const (
	TelemetryQualityGood      TelemetryQuality = "GOOD"
	TelemetryQualityPartial   TelemetryQuality = "PARTIAL"
	TelemetryQualityEstimated TelemetryQuality = "ESTIMATED"
	TelemetryQualityManual    TelemetryQuality = "MANUAL"
	TelemetryQualityStale     TelemetryQuality = "STALE"
	TelemetryQualityInvalid   TelemetryQuality = "INVALID"
)

type TelemetryReadiness string

const (
	TelemetryReadinessCurrent       TelemetryReadiness = "CURRENT"
	TelemetryReadinessDegraded      TelemetryReadiness = "DEGRADED"
	TelemetryReadinessIncomplete    TelemetryReadiness = "INCOMPLETE"
	TelemetryReadinessNotApplicable TelemetryReadiness = "NOT_APPLICABLE"
)

type DeviceDisplayState string

const (
	DeviceDisplayStateOnline      DeviceDisplayState = "ONLINE"
	DeviceDisplayStateOffline     DeviceDisplayState = "OFFLINE"
	DeviceDisplayStateStale       DeviceDisplayState = "STALE"
	DeviceDisplayStateUnknown     DeviceDisplayState = "UNKNOWN"
	DeviceDisplayStateUnavailable DeviceDisplayState = "UNAVAILABLE"
)

type QualityReasonCode string

const (
	QualityReasonCodeSourceUntrusted   QualityReasonCode = "SOURCE_UNTRUSTED"
	QualityReasonCodeTypeMismatch      QualityReasonCode = "TYPE_MISMATCH"
	QualityReasonCodeUnitMismatch      QualityReasonCode = "UNIT_MISMATCH"
	QualityReasonCodeOutOfRange        QualityReasonCode = "OUT_OF_RANGE"
	QualityReasonCodeClockAhead        QualityReasonCode = "CLOCK_AHEAD"
	QualityReasonCodeClockBehind       QualityReasonCode = "CLOCK_BEHIND"
	QualityReasonCodeSourceLagExceeded QualityReasonCode = "SOURCE_LAG_EXCEEDED"
	QualityReasonCodeDuplicate         QualityReasonCode = "DUPLICATE"
	QualityReasonCodeOutOfOrder        QualityReasonCode = "OUT_OF_ORDER"
	QualityReasonCodeReplayed          QualityReasonCode = "REPLAYED"
)

type AvailabilityReasonCode string

const (
	AvailabilityReasonCodeSourceUnavailable          AvailabilityReasonCode = "SOURCE_UNAVAILABLE"
	AvailabilityReasonCodeObservationCoverageGap     AvailabilityReasonCode = "OBSERVATION_COVERAGE_GAP"
	AvailabilityReasonCodePolicyUnavailable          AvailabilityReasonCode = "POLICY_UNAVAILABLE"
	AvailabilityReasonCodeOwnerDependencyUnavailable AvailabilityReasonCode = "OWNER_DEPENDENCY_UNAVAILABLE"
)

type TelemetryValue = json.RawMessage

type LastKnownPresence struct {
	State          DevicePresenceState `json:"state"`
	LastSeenAt     *Instant            `json:"lastSeenAt"`
	EvaluatedAt    Instant             `json:"evaluatedAt"`
	PolicyRevision PolicyRevision      `json:"policyRevision"`
}

type PresenceSnapshot struct {
	Applicability  PresenceApplicability `json:"applicability"`
	CurrentState   *DevicePresenceState  `json:"currentState"`
	LastSeenAt     *Instant              `json:"lastSeenAt"`
	PolicyRevision *PolicyRevision       `json:"policyRevision"`
	LastKnown      *LastKnownPresence    `json:"lastKnown"`
}

type TelemetryPresentState struct {
	Key            TelemetryKey        `json:"key"`
	State          string              `json:"state"`
	Value          TelemetryValue      `json:"value"`
	ValueType      string              `json:"valueType"`
	Unit           *string             `json:"unit"`
	SampledAt      Instant             `json:"sampledAt"`
	ReceivedAt     Instant             `json:"receivedAt"`
	Freshness      string              `json:"freshness"`
	Quality        TelemetryQuality    `json:"quality"`
	QualityReasons []QualityReasonCode `json:"qualityReasons"`
	PolicyRevision PolicyRevision      `json:"policyRevision"`
}

type TelemetryMissingState struct {
	Key            TelemetryKey    `json:"key"`
	State          string          `json:"state"`
	Freshness      string          `json:"freshness"`
	MissingReason  string          `json:"missingReason"`
	PolicyRevision *PolicyRevision `json:"policyRevision"`
}

type TelemetryKeyState struct {
	Present *TelemetryPresentState
	Missing *TelemetryMissingState
}

func (value TelemetryKeyState) MarshalJSON() ([]byte, error) {
	switch {
	case value.Present != nil && value.Missing == nil:
		return json.Marshal(value.Present)
	case value.Missing != nil && value.Present == nil:
		return json.Marshal(value.Missing)
	default:
		return nil, fmt.Errorf("telemetry key state must contain exactly one variant")
	}
}

func (value *TelemetryKeyState) UnmarshalJSON(data []byte) error {
	var discriminator struct {
		State string `json:"state"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return err
	}
	switch discriminator.State {
	case "PRESENT":
		var present TelemetryPresentState
		if err := json.Unmarshal(data, &present); err != nil {
			return err
		}
		value.Present, value.Missing = &present, nil
	case "MISSING":
		var missing TelemetryMissingState
		if err := json.Unmarshal(data, &missing); err != nil {
			return err
		}
		value.Present, value.Missing = nil, &missing
	default:
		return fmt.Errorf("unsupported telemetry key state %q", discriminator.State)
	}
	return nil
}

type DeviceObservationSnapshot struct {
	SchemaVersion          int                      `json:"schemaVersion"`
	DeviceId               UUIDv7                   `json:"deviceId"`
	TenantId               UUIDv7                   `json:"tenantId"`
	SiteId                 UUIDv7                   `json:"siteId"`
	BusinessRevision       BusinessRevision         `json:"businessRevision"`
	EvaluatedAt            Instant                  `json:"evaluatedAt"`
	EvaluationAvailability EvaluationAvailability   `json:"evaluationAvailability"`
	AvailabilityReasons    []AvailabilityReasonCode `json:"availabilityReasons"`
	Presence               PresenceSnapshot         `json:"presence"`
	TelemetryReadiness     TelemetryReadiness       `json:"telemetryReadiness"`
	DisplayState           *DeviceDisplayState      `json:"displayState"`
	Values                 []TelemetryKeyState      `json:"values"`
}

type ObservationSnapshotTarget struct {
	RequestId string         `json:"requestId"`
	DeviceId  UUIDv7         `json:"deviceId"`
	Keys      []TelemetryKey `json:"keys"`
}

type BatchGetObservationSnapshotsRequest struct {
	Requests []ObservationSnapshotTarget `json:"requests"`
}

type BatchObservationSuccess struct {
	RequestId string                    `json:"requestId"`
	DeviceId  UUIDv7                    `json:"deviceId"`
	Status    string                    `json:"status"`
	Snapshot  DeviceObservationSnapshot `json:"snapshot"`
}

type BatchObservationFailure struct {
	RequestId string         `json:"requestId"`
	DeviceId  UUIDv7         `json:"deviceId"`
	Status    string         `json:"status"`
	Problem   ProblemDetails `json:"problem"`
}

type BatchObservationResult struct {
	Success *BatchObservationSuccess
	Failure *BatchObservationFailure
}

func (value BatchObservationResult) MarshalJSON() ([]byte, error) {
	switch {
	case value.Success != nil && value.Failure == nil:
		return json.Marshal(value.Success)
	case value.Failure != nil && value.Success == nil:
		return json.Marshal(value.Failure)
	default:
		return nil, fmt.Errorf("batch observation result must contain exactly one variant")
	}
}

func (value *BatchObservationResult) UnmarshalJSON(data []byte) error {
	var discriminator struct {
		Status string `json:"status"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return err
	}
	switch discriminator.Status {
	case "OK":
		var success BatchObservationSuccess
		if err := json.Unmarshal(data, &success); err != nil {
			return err
		}
		value.Success, value.Failure = &success, nil
	case "ERROR":
		var failure BatchObservationFailure
		if err := json.Unmarshal(data, &failure); err != nil {
			return err
		}
		value.Success, value.Failure = nil, &failure
	default:
		return fmt.Errorf("unsupported batch observation result %q", discriminator.Status)
	}
	return nil
}

type BatchGetObservationSnapshotsResponse struct {
	SchemaVersion int                      `json:"schemaVersion"`
	Items         []BatchObservationResult `json:"items"`
}

type SubscriptionTargetRequest struct {
	ClientSubscriptionId ClientSubscriptionId  `json:"clientSubscriptionId"`
	DeviceId             UUIDv7                `json:"deviceId"`
	Keys                 []TelemetryKey        `json:"keys"`
	RecoveryCursor       *OpaqueRecoveryCursor `json:"recoveryCursor,omitempty"`
}

type SubscriptionBootstrapRequest struct {
	Subscriptions []SubscriptionTargetRequest `json:"subscriptions"`
}

type TransportPosition struct {
	Epoch  string `json:"epoch"`
	Offset int64  `json:"offset"`
}

type SubscriptionDescriptor struct {
	ClientSubscriptionId ClientSubscriptionId  `json:"clientSubscriptionId"`
	SubscriptionId       OpaqueSubscriptionId  `json:"subscriptionId"`
	DeviceId             UUIDv7                `json:"deviceId"`
	Keys                 []TelemetryKey        `json:"keys"`
	Channel              OpaqueChannel         `json:"channel"`
	RecoveryMode         string                `json:"recoveryMode"`
	TransportPosition    *TransportPosition    `json:"transportPosition"`
	RecoveryCursor       *OpaqueRecoveryCursor `json:"recoveryCursor"`
}

type SubscriptionLimits struct {
	MaxSubscriptions       int `json:"maxSubscriptions"`
	MaxKeysPerSubscription int `json:"maxKeysPerSubscription"`
	MaxTotalKeySelections  int `json:"maxTotalKeySelections"`
}

type SubscriptionBootstrapResponse struct {
	SchemaVersion     int                      `json:"schemaVersion"`
	TransportProtocol string                   `json:"transportProtocol"`
	Endpoint          string                   `json:"endpoint"`
	ConnectionToken   string                   `json:"connectionToken"`
	ExpiresAt         Instant                  `json:"expiresAt"`
	Subscriptions     []SubscriptionDescriptor `json:"subscriptions"`
	Limits            SubscriptionLimits       `json:"limits"`
}

type RecoveryCursorCheckpoint struct {
	SubscriptionId    OpaqueSubscriptionId `json:"subscriptionId"`
	BusinessRevision  BusinessRevision     `json:"businessRevision"`
	TransportPosition TransportPosition    `json:"transportPosition"`
}

type RecoveryCursorCheckpointRequest struct {
	Checkpoints []RecoveryCursorCheckpoint `json:"checkpoints"`
}

type RecoveryCursorCheckpointResult struct {
	SubscriptionId   OpaqueSubscriptionId `json:"subscriptionId"`
	BusinessRevision BusinessRevision     `json:"businessRevision"`
	RecoveryCursor   OpaqueRecoveryCursor `json:"recoveryCursor"`
	ExpiresAt        Instant              `json:"expiresAt"`
}

type RecoveryCursorCheckpointResponse struct {
	SchemaVersion int                              `json:"schemaVersion"`
	Items         []RecoveryCursorCheckpointResult `json:"items"`
}

type HistoryInstant string

type DeviceHistoryQuality string

const (
	DeviceHistoryQualityGood      DeviceHistoryQuality = "GOOD"
	DeviceHistoryQualityPartial   DeviceHistoryQuality = "PARTIAL"
	DeviceHistoryQualityEstimated DeviceHistoryQuality = "ESTIMATED"
	DeviceHistoryQualityManual    DeviceHistoryQuality = "MANUAL"
	DeviceHistoryQualityStale     DeviceHistoryQuality = "STALE"
	DeviceHistoryQualityInvalid   DeviceHistoryQuality = "INVALID"
)

type DeviceHistoryAcceptance string

const (
	DeviceHistoryAcceptanceAccepted   DeviceHistoryAcceptance = "ACCEPTED"
	DeviceHistoryAcceptanceOutOfOrder DeviceHistoryAcceptance = "OUT_OF_ORDER"
)

type DeviceHistoryValueType string

const (
	DeviceHistoryValueTypeNumber  DeviceHistoryValueType = "NUMBER"
	DeviceHistoryValueTypeString  DeviceHistoryValueType = "STRING"
	DeviceHistoryValueTypeBoolean DeviceHistoryValueType = "BOOLEAN"
	DeviceHistoryValueTypeJson    DeviceHistoryValueType = "JSON"
)

type DeviceHistoryPointType string

const (
	DeviceHistoryPointTypeTelemetry DeviceHistoryPointType = "TELEMETRY"
	DeviceHistoryPointTypeCounter   DeviceHistoryPointType = "COUNTER"
	DeviceHistoryPointTypeState     DeviceHistoryPointType = "STATE"
	DeviceHistoryPointTypeSetting   DeviceHistoryPointType = "SETTING"
	DeviceHistoryPointTypeCommand   DeviceHistoryPointType = "COMMAND"
)

type DeviceHistoryRequest struct {
	DeviceId UUIDv7         `json:"deviceId"`
	Keys     []TelemetryKey `json:"keys"`
	From     HistoryInstant `json:"from"`
	To       HistoryInstant `json:"to"`
	PageSize int            `json:"pageSize"`
	Cursor   *string        `json:"cursor,omitempty"`
}

type DeviceHistorySourcePosition struct {
	Partition string `json:"partition"`
	Offset    int64  `json:"offset"`
	EventId   UUIDv7 `json:"eventId"`
}

type DeviceHistoryObservation struct {
	ObservationId  UUIDv7                      `json:"observationId"`
	TelemetryKey   TelemetryKey                `json:"telemetryKey"`
	PointId        UUIDv7                      `json:"pointId"`
	SensorId       *UUIDv7                     `json:"sensorId"`
	PointType      DeviceHistoryPointType      `json:"pointType"`
	PointRevision  int64                       `json:"pointRevision"`
	SampledAt      HistoryInstant              `json:"sampledAt"`
	ReceivedAt     HistoryInstant              `json:"receivedAt"`
	Acceptance     DeviceHistoryAcceptance     `json:"acceptance"`
	ValueType      DeviceHistoryValueType      `json:"valueType"`
	Value          TelemetryValue              `json:"value"`
	Unit           *string                     `json:"unit"`
	Quality        DeviceHistoryQuality        `json:"quality"`
	QualityReasons []string                    `json:"qualityReasons"`
	SourcePosition DeviceHistorySourcePosition `json:"sourcePosition"`
}

type DeviceHistoryMetadata struct {
	RequestedFrom        HistoryInstant  `json:"requestedFrom"`
	RequestedTo          HistoryInstant  `json:"requestedTo"`
	ProjectionWatermark  *HistoryInstant `json:"projectionWatermark"`
	PageSize             int             `json:"pageSize"`
	ReturnedObservations int             `json:"returnedObservations"`
	NextCursor           *string         `json:"nextCursor"`
}

type DeviceHistoryResponse struct {
	SchemaVersion int                        `json:"schemaVersion"`
	TenantId      UUIDv7                     `json:"tenantId"`
	SiteId        UUIDv7                     `json:"siteId"`
	DeviceId      UUIDv7                     `json:"deviceId"`
	Observations  []DeviceHistoryObservation `json:"observations"`
	Metadata      DeviceHistoryMetadata      `json:"metadata"`
}

type DeviceHistoryAggregateGranularity string

const (
	DeviceHistoryAggregateGranularityHour  DeviceHistoryAggregateGranularity = "HOUR"
	DeviceHistoryAggregateGranularityDay   DeviceHistoryAggregateGranularity = "DAY"
	DeviceHistoryAggregateGranularityWeek  DeviceHistoryAggregateGranularity = "WEEK"
	DeviceHistoryAggregateGranularityMonth DeviceHistoryAggregateGranularity = "MONTH"
)

type DeviceHistoryAggregateQualityPolicy string

const (
	DeviceHistoryAggregateQualityPolicyValidOnly DeviceHistoryAggregateQualityPolicy = "VALID_ONLY"
	DeviceHistoryAggregateQualityPolicyUsable    DeviceHistoryAggregateQualityPolicy = "USABLE"
)

type DeviceHistoryAggregateRequest struct {
	DeviceId      UUIDv7                              `json:"deviceId"`
	Keys          []TelemetryKey                      `json:"keys"`
	From          HistoryInstant                      `json:"from"`
	To            HistoryInstant                      `json:"to"`
	Granularity   DeviceHistoryAggregateGranularity   `json:"granularity"`
	Timezone      string                              `json:"timezone"`
	QualityPolicy DeviceHistoryAggregateQualityPolicy `json:"qualityPolicy"`
}

type DeviceHistoryAggregateQualitySummary struct {
	Good      int64 `json:"good"`
	Partial   int64 `json:"partial"`
	Estimated int64 `json:"estimated"`
	Manual    int64 `json:"manual"`
	Stale     int64 `json:"stale"`
	Invalid   int64 `json:"invalid"`
}

type DeviceHistoryGaugeAggregate struct {
	Average     float64 `json:"average"`
	Minimum     float64 `json:"minimum"`
	Maximum     float64 `json:"maximum"`
	First       float64 `json:"first"`
	Last        float64 `json:"last"`
	SampleCount int64   `json:"sampleCount"`
}

type DeviceHistoryCounterAggregate struct {
	DeltaSum                float64 `json:"deltaSum"`
	DeltaCount              int64   `json:"deltaCount"`
	ResetCount              int64   `json:"resetCount"`
	RolloverCount           int64   `json:"rolloverCount"`
	ExcludedTransitionCount int64   `json:"excludedTransitionCount"`
}

type DeviceHistoryStateAggregate struct {
	ValueType   DeviceHistoryValueType `json:"valueType"`
	LastValue   TelemetryValue         `json:"lastValue"`
	SampleCount int64                  `json:"sampleCount"`
	ChangeCount int64                  `json:"changeCount"`
}

type DeviceHistoryAggregateBucket struct {
	TelemetryKey  TelemetryKey                         `json:"telemetryKey"`
	PointId       UUIDv7                               `json:"pointId"`
	PointRevision int64                                `json:"pointRevision"`
	PointType     string                               `json:"pointType"`
	Unit          *string                              `json:"unit"`
	PeriodStart   HistoryInstant                       `json:"periodStart"`
	PeriodEnd     HistoryInstant                       `json:"periodEnd"`
	Quality       DeviceHistoryAggregateQualitySummary `json:"quality"`
	Completeness  float64                              `json:"completeness"`
	Gauge         *DeviceHistoryGaugeAggregate         `json:"gauge,omitempty"`
	Counter       *DeviceHistoryCounterAggregate       `json:"counter,omitempty"`
	State         *DeviceHistoryStateAggregate         `json:"state,omitempty"`
}

type DeviceHistoryAggregateMetadata struct {
	RequestedFrom       HistoryInstant                      `json:"requestedFrom"`
	RequestedTo         HistoryInstant                      `json:"requestedTo"`
	Granularity         DeviceHistoryAggregateGranularity   `json:"granularity"`
	Timezone            string                              `json:"timezone"`
	QualityPolicy       DeviceHistoryAggregateQualityPolicy `json:"qualityPolicy"`
	ProjectionWatermark *HistoryInstant                     `json:"projectionWatermark"`
	ReturnedBuckets     int                                 `json:"returnedBuckets"`
}

type DeviceHistoryAggregateResponse struct {
	SchemaVersion int                            `json:"schemaVersion"`
	TenantId      UUIDv7                         `json:"tenantId"`
	SiteId        UUIDv7                         `json:"siteId"`
	DeviceId      UUIDv7                         `json:"deviceId"`
	Buckets       []DeviceHistoryAggregateBucket `json:"buckets"`
	Metadata      DeviceHistoryAggregateMetadata `json:"metadata"`
}

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type ProblemDetails struct {
	Type         string       `json:"type"`
	Title        string       `json:"title"`
	Status       int          `json:"status"`
	Detail       string       `json:"detail"`
	Instance     string       `json:"instance"`
	Code         string       `json:"code"`
	TraceId      string       `json:"traceId"`
	Retryable    bool         `json:"retryable"`
	RetryAfterMs *int         `json:"retryAfterMs,omitempty"`
	FieldErrors  []FieldError `json:"fieldErrors,omitempty"`
}

type DeviceObservationPublication struct {
	SchemaVersion          int                      `json:"schemaVersion"`
	Kind                   string                   `json:"kind"`
	EventId                UUIDv7                   `json:"eventId"`
	SubscriptionId         OpaqueSubscriptionId     `json:"subscriptionId"`
	DeviceId               UUIDv7                   `json:"deviceId"`
	PreviousRevision       BusinessRevision         `json:"previousRevision"`
	Revision               BusinessRevision         `json:"revision"`
	EvaluatedAt            Instant                  `json:"evaluatedAt"`
	PublishedAt            Instant                  `json:"publishedAt"`
	EvaluationAvailability EvaluationAvailability   `json:"evaluationAvailability"`
	AvailabilityReasons    []AvailabilityReasonCode `json:"availabilityReasons"`
	Presence               PresenceSnapshot         `json:"presence"`
	TelemetryReadiness     TelemetryReadiness       `json:"telemetryReadiness"`
	DisplayState           *DeviceDisplayState      `json:"displayState"`
	TelemetryChanges       []TelemetryKeyState      `json:"telemetryChanges"`
}
