apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmaps.yaml
  - secret-provider-class.yaml
  - services.yaml
  - disruption-budgets.yaml
  - networkpolicies.yaml
  - migration-job.yaml
  - workloads/command-service.yaml
  - workloads/command-dispatcher.yaml
  - workloads/command-verifier.yaml
