apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: s3-command-service-database
  namespace: s3-certification
spec:
  provider: "[CLOUD_SECRET_PROVIDER]"
  parameters:
    objects: |
      [PROVIDER_SPECIFIC_OBJECTS_RENDERING_COMMAND_SERVICE_DSN_FILE]
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: s3-command-migrator-database
  namespace: s3-certification
spec:
  provider: "[CLOUD_SECRET_PROVIDER]"
  parameters:
    objects: |
      [PROVIDER_SPECIFIC_OBJECTS_RENDERING_COMMAND_MIGRATOR_PGSERVICE_FILE]
