apiVersion: v1
kind: ServiceAccount
metadata:
  name: command-service
  namespace: s3-certification
  annotations:
    s3.hvac/workload-identity-reference: workload://[PROVIDER]/[CLUSTER]/s3-certification/command-service
    s3.hvac/certificate-approval-policy: policy://[PROVIDER]/[CLUSTER]/cert-manager/command-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: command-dispatcher
  namespace: s3-certification
  annotations:
    s3.hvac/workload-identity-reference: workload://[PROVIDER]/[CLUSTER]/s3-certification/command-dispatcher
    s3.hvac/certificate-approval-policy: policy://[PROVIDER]/[CLUSTER]/cert-manager/command-dispatcher
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: command-verifier
  namespace: s3-certification
  annotations:
    s3.hvac/workload-identity-reference: workload://[PROVIDER]/[CLUSTER]/s3-certification/command-verifier
    s3.hvac/certificate-approval-policy: policy://[PROVIDER]/[CLUSTER]/cert-manager/command-verifier
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-command-migrator
  namespace: s3-certification
  annotations:
    s3.hvac/workload-identity-reference: workload://[PROVIDER]/[CLUSTER]/s3-certification/s3-command-migrator
automountServiceAccountToken: false
