import type {
  ControlCommandItem,
  ControlFilterParams,
  ControlStrategyItem,
  ControlWorkspaceData,
  SafetyInterlockRule,
} from './control-types';

export const controlService = {
  async getControlWorkspaceData(
    _params?: ControlFilterParams
  ): Promise<ControlWorkspaceData> {
    const summary = {
      activeAuthority: 'AI_CLOSED_LOOP' as const,
      activeAuthorityLabel: 'AI 闭环调优托管',
      bacnetPriority: 10,
      activeOverrideCount: 0,
      readbackAlignmentPercent: 100,
      safetyInterlockStatus: 'ALL_PASSED' as const,
      securityLevel: 'Level 2 · 变频与温控授权',
      todayCommandCount: 142,
    };

    const strategies: readonly ControlStrategyItem[] = [
      {
        id: 'STRAT-01',
        name: '冷源站全局自适应能效寻优闭环 (MPC)',
        code: 'CHILLER_PLANT_MPC_OPT',
        status: 'ACTIVE',
        description:
          '基于负荷预测与热力学模型，动态闭环重置冷冻水供水温度 (7.0~8.5°C)、冷机加减载顺序、变频水泵流量与冷却塔逼近度',
        expectedSavingsPercent: 13.5,
        parameters: [
          { name: '冷冻水供水温度区间', value: '7.0 ~ 8.5 °C', defaultVal: '7.0 °C' },
          { name: '水泵变频频率下限', value: '35.0 Hz', defaultVal: '40.0 Hz' },
          { name: '冷却塔逼近度目标', value: '2.8 K', defaultVal: '3.5 K' },
          { name: '冷机加减载死区时间', value: '20 min', defaultVal: '15 min' },
        ],
        lastActivatedAt: '2026-09-30 06:00:00',
        author: '系统能效优化引擎 v4.2',
      },
      {
        id: 'STRAT-02',
        name: '尖峰用电需量平抑与响应调度',
        code: 'PEAK_DEMAND_SHEDDING',
        status: 'STANDBY',
        description:
          '在尖峰电价时段 (12:00~14:00, 19:00~21:00) 自动平抑冷源瞬时功率，柔性下调冷机负荷上限 15%，优先保障契约需量安全',
        expectedSavingsPercent: 8.2,
        parameters: [
          { name: '需量红线安全裕量', value: '10% (2520 kW)', defaultVal: '2800 kW' },
          { name: '冷机最大限制出力', value: '80% RLA', defaultVal: '100% RLA' },
          { name: '末端送风温度浮动', value: '+1.0 K', defaultVal: '0.0 K' },
        ],
        lastActivatedAt: '2026-09-29 19:00:00',
        author: '负荷需量调度模块',
      },
      {
        id: 'STRAT-03',
        name: '恒定基准排程控制策略 (保底模式)',
        code: 'BASELINE_SCHEDULED',
        status: 'STANDBY',
        description:
          '传统BAS定时定值控制，固定冷冻水供水温度 7.0°C、冷却水出水温度 32.0°C，水泵按工频/恒速设定运行',
        expectedSavingsPercent: 0.0,
        parameters: [
          { name: '固定供水设定', value: '7.0 °C', defaultVal: '7.0 °C' },
          { name: '运行时间段', value: '07:00 ~ 22:00', defaultVal: '全天' },
        ],
        lastActivatedAt: '2026-09-20 00:00:00',
        author: '工程运维部',
      },
      {
        id: 'STRAT-04',
        name: '过渡季免费供冷经济器模式 (板换)',
        code: 'FREE_COOLING_ECONOMIZER',
        status: 'CANDIDATE',
        description:
          '室外湿球温度低至 10°C 以下时自动停运冷机，开启板式换热器利用冷却塔冷水直接为末端供冷',
        expectedSavingsPercent: 22.0,
        parameters: [
          { name: '湿球温度触发阈值', value: '≤ 10.0 °C', defaultVal: '8.0 °C' },
          { name: '板换旁通电动阀开度', value: '100%', defaultVal: '0%' },
        ],
        lastActivatedAt: '—',
        author: '系统规划工程师',
      },
    ];

    const commands: readonly ControlCommandItem[] = [
      {
        id: 'CMD-20260930-0142',
        targetAssetId: 'CH-01',
        targetAssetName: '1# 离心冷水机组',
        capability: 'SET_LOAD_LIMIT',
        capabilityLabel: '冷机负荷上限调节',
        requestedValue: '85.0',
        readbackValue: '85.0',
        unit: '%',
        priority: 10,
        state: 'VERIFIED',
        interlocksPassed: true,
        preconditions: ['水流开关正常闭合', '无未复位机械故障', '排气压力低于限值'],
        operator: 'AI 寻优引擎',
        executedAt: '19:28:15',
        impactRadius: '1# 离心机单机负荷与瞬时能耗',
        reason: '负荷预测微幅下降，自适应调优冷机分摊比例',
      },
      {
        id: 'CMD-20260930-0141',
        targetAssetId: 'LOOP-01',
        targetAssetName: '冷冻水供水总管',
        capability: 'SET_CHILLED_WATER_TEMPERATURE_SETPOINT',
        capabilityLabel: '冷冻水供水设定值重置',
        requestedValue: '7.2',
        readbackValue: '7.2',
        unit: '°C',
        priority: 10,
        state: 'READBACK_MATCHED',
        interlocksPassed: true,
        preconditions: ['末端最不利环路温差 > 4.5K', '末端区域湿度 < 65%'],
        operator: 'AI 寻优引擎',
        executedAt: '19:15:00',
        impactRadius: '冷站全系统供水温度与机组蒸发温度',
        reason: '室外气温下降至 24.5°C，提升供水温度 0.2°C 降低冷机压比',
      },
      {
        id: 'CMD-20260930-0140',
        targetAssetId: 'CHWP-01',
        targetAssetName: '1# 冷冻水一次泵',
        capability: 'SET_FREQUENCY',
        capabilityLabel: '变频工作频率设定',
        requestedValue: '43.5',
        readbackValue: '43.5',
        unit: 'Hz',
        priority: 10,
        state: 'VERIFIED',
        interlocksPassed: true,
        preconditions: ['最不利环路压差 ≥ 0.20 MPa', '电机温度正常'],
        operator: 'AI 寻优引擎',
        executedAt: '19:00:22',
        impactRadius: '一次泵循环流量与水力平衡',
        reason: '恒压差自适应追踪调节',
      },
      {
        id: 'CMD-20260930-0139',
        targetAssetId: 'CWP-01',
        targetAssetName: '1# 冷却水循环泵',
        capability: 'SET_FREQUENCY',
        capabilityLabel: '变频工作频率设定',
        requestedValue: '46.2',
        readbackValue: '46.2',
        unit: 'Hz',
        priority: 10,
        state: 'VERIFIED',
        interlocksPassed: true,
        preconditions: ['冷却塔进水阀全开', '出水温度正常'],
        operator: 'AI 寻优引擎',
        executedAt: '18:45:10',
        impactRadius: '冷却水循环流量',
        reason: '逼近度优化调节',
      },
      {
        id: 'CMD-20260930-0138',
        targetAssetId: 'CT-01',
        targetAssetName: '1# 开式超静音冷却塔',
        capability: 'SET_FAN_SPEED',
        capabilityLabel: '冷却塔风机转速设定',
        requestedValue: '82.0',
        readbackValue: '82.0',
        unit: '%',
        priority: 10,
        state: 'VERIFIED',
        interlocksPassed: true,
        preconditions: ['风机振动传感器正常', '集水盘水位正常'],
        operator: 'AI 寻优引擎',
        executedAt: '18:30:00',
        impactRadius: '冷却塔散热量与出水温度',
        reason: '维持 26.8°C 最佳冷却水温',
      },
      {
        id: 'CMD-20260930-0137',
        targetAssetId: 'VALVE-BYPASS',
        targetAssetName: '定压差旁通调节阀',
        capability: 'SET_OPENING',
        capabilityLabel: '调节阀开度设定',
        requestedValue: '12.0',
        readbackValue: '12.0',
        unit: '%',
        priority: 10,
        state: 'VERIFIED',
        interlocksPassed: true,
        preconditions: ['系统压差 > 0.22 MPa'],
        operator: '定压差保护控制器',
        executedAt: '18:15:30',
        impactRadius: '分水器/集水器水力平衡',
        reason: '平抑末端关闭引起的轻微水力冲击',
      },
    ];

    const interlocks: readonly SafetyInterlockRule[] = [
      {
        id: 'INT-01',
        name: '冷水机组蒸发器水流断流紧急保护联锁',
        scope: '全部冷水机组 (CH-01 ~ CH-03)',
        condition: '冷冻水靶式水流开关断开持续超过 3 秒',
        action: '立即触发冷机安全停机，并闭锁开机指令',
        status: 'HEALTHY',
        lastTested: '2026-09-28 10:00:00 (自动巡检正常)',
      },
      {
        id: 'INT-02',
        name: '冷凝器排气超压机械与电气切断保护',
        scope: '全部冷水机组',
        condition: '冷凝绝对压力超过 1.25 MPa',
        action: '硬件继电器直接切断压缩机接触器供电',
        status: 'HEALTHY',
        lastTested: '2026-09-25 15:30:00 (检验合格)',
      },
      {
        id: 'INT-03',
        name: '大功率压缩机最小启停保护间隔 (防频繁启停)',
        scope: '离心冷机电机',
        condition: '机组停机后再次启动时间间隔 < 15 分钟',
        action: '软硬件闭锁开机请求，倒计时结束后方可释放',
        status: 'HEALTHY',
        lastTested: '常驻激活',
      },
      {
        id: 'INT-04',
        name: '水泵变频器最低工作频率防气蚀与散热保护',
        scope: '冷冻/冷却循环水泵',
        condition: '变频频率指令 < 30.0 Hz',
        action: '强制钳位在最低安全频率 30.0 Hz',
        status: 'HEALTHY',
        lastTested: '常驻激活',
      },
      {
        id: 'INT-05',
        name: 'BACnet / Modbus 工业总线通信超时脱机保护',
        scope: '边缘控制网关',
        condition: '云端控制心跳丢失超过 60 秒',
        action: '自动回退至本地控制器预设基准排程模式',
        status: 'HEALTHY',
        lastTested: '2026-09-29 02:00:00 (脱机演练成功)',
      },
    ];

    return {
      summary,
      strategies,
      commands,
      interlocks,
    };
  },
};
